### ISSUE TITLE
Inability to Deselect Avatar NFT without Selecting Another

### ISSUE THREAD

**Issue by hadiamjad** [brave/brave-talk#1087]
Currently in Avatar NFTs selection, there is a restriction allowing users to choose only one avatar at a time, which is generally acceptable. However, an issue arises when a user decides to deselect their chosen Avatar NFT, leaving them without an avatar altogether. The current UI does not support the option to simply remove the selected Avatar NFT without immediately selecting an alternative.

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/brave-talk/pull/1103
