### ISSUE TITLE
Not all available NFTs are shown to be selected as Avatars

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1088]
### Description
Not all available NFTs are shown to be selected as Avatars

### Steps to reproduce
1. Have a bunch of NFTs in wallet 
2. Create a Web3 Talk room
3. Only few selected NFTs are shown to be selected as Avatars

### Actual result
![image](https://github.com/brave/brave-talk/assets/17010094/79a8e4a9-5322-4e44-9576-caf2c8757961)

### Expected result
Provide all NFTs for user to select as Avatar

### Additional info
cc: @mrose17 @nvonpentz

**Comment by mrose17** [comment]
@srirambv - there is a filtering function. can you right-click on each of the responses you'll see the console, do "Copy object" on each, and DM the results to @hadiamjad and myself.

@hadiamjad - can you add a checkbox associated with the "Avatar NFT" box that indicates whether to "Show all NFTs". The default should be off. If the user turns it on, then show all the NFTs. (Hint: don't make another API call, we get all the NFTs when we make the all, so just return the (un)filtered list as appropriate!

**Comment by srirambv** [comment]
Discussed it [here](https://bravesoftware.slack.com/archives/C05FLURB4AC/p1688450188297989). Indeed spam score being high is the cause of it. But irrespective of spam score we should show the NFTs so user can still choose to select which ever NFT they want.

**Comment by srirambv** [comment]
I can see the checkbox for `Show NFTs with Less Spam Score`. 

https://github.com/brave/brave-talk/assets/17010094/ef9c06d9-b1db-4cd8-b24c-96e79a4d92c6



@hadiamjad maybe we should have it as `Show NFTs with less Spam Score` instead of `Show NFTs with Less Spam Score`

**Comment by mrose17** [comment]
@hadiamjad - I suggest the following:
1. If all NFTs are below the spam score, then no checkbox, just the text "Showing all NFTs for your address". Otherwise,
2. If the box is checked, the text should be "Show all NFTs".
3. If the box is not checked, the text should be "Show all NFTs (not all being shown)".
4. I would use the exact text and capitalization above. We can then show it to Matt to get the final edits!

**Comment by hadiamjad** [comment]
Fixed and deployed!
<img width="583" alt="image" src="https://github.com/brave/brave-talk/assets/46374292/dd3f1169-8cad-41ba-9172-b3fa8b2f7bfb">
