### ISSUE TITLE
Auto-detect and switch the account to join the call seamlessly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1089]
### Description
Currently when you join a Web3 call it takes the current active account to connect and sign message to join. Chances are if the user is having Ethereum as current active account and tries to join a Solana NFT gated Web3 call, the process goes through for connection and signing message and joining fails so either the user has to manually change the account and reload the page to connect again or start the process again by removing the connected state and start over. It would be good to detect the call type and only provide an option to connect that network accounts to connect with.

### Steps to reproduce
1. Setup a Web3 call using Solana NFT on device 1
2. On device 2, have Ethereum account selected as active account
3. Try to join the call on device 2 using the Web3  room link created in step 1
4. Connect wallet and sign message shows the current active account which is Ethereum
5. Sign message is success but fails to join since it requires Solana NFT 
6. Repeat process switching Ethereum and Solana on both devices

### Actual result
Able to connect and sign with active account irrespective of what type of NFT is used to gate the call

### Expected result
Smart detection of NFTs/POAP requirement to join the call and show/switch to that account to join

### Additional Information
cc: @mrose17 @Douglashdaniel @josheleonard

**Comment by srirambv** [comment]
This is still an issue on Dev server. I have created a talk link with Solana account and when trying to join on a different browser it only shows Ethereum accounts to connect.

**Comment by hadiamjad** [comment]
@srirambv Just to be clear which wallet are you using?

**Comment by srirambv** [comment]
Call is created on Brave Beta and trying to join via Brave Release. Also same issue with just Phantom wallet on Edge.

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/brave-talk/pull/1206
