### ISSUE TITLE
Show proper error message for BAT Token gating 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1111]
### Description
Show proper error message for BAT Token gating 

### Steps to reproduce

1. Create a Web3 Talk with BAT token gating
2. Join the call with a zero BAT wallet
3. Shows `Not listed as a participant` but console shows ` You must have an approved token to join this call` 

### Actual Result
![image](https://github.com/brave/brave-talk/assets/17010094/bd667d24-fea9-4ab7-aa26-9c1738b8c9b2)

### Expected Result
Show correct error message

### Additional Information
cc: @mrose17

**Comment by srirambv** [comment]
This is updated now.
![image](https://github.com/brave/brave-talk/assets/17010094/6daac2bd-7df2-4c0a-8a0a-3f12284f5431)

May need to update the text to mention about token balance as a criteria to join.

**Comment by mrose17** [comment]
The diagnostic should mention the token (e.g., "BAT") and the amount...

**Comment by srirambv** [comment]
This is updated now on both the screen for creating call and joining call

![image](https://github.com/brave/brave-talk/assets/17010094/904c7ec2-0cfc-48f2-b35e-f6c4448c103b) | ![image](https://github.com/brave/brave-talk/assets/17010094/1e2579d5-2c4d-4080-b82f-bc46064ce129)
-- | --

**Comment by srirambv** [comment]
This is fixed on Dev2
![image](https://github.com/brave/brave-talk/assets/17010094/427c1e35-a29c-41bd-8eda-a121812e0dba)

**Comment by srirambv** [comment]
This is fixed on Dev2 
![image](https://github.com/brave/brave-talk/assets/17010094/de73dd8f-667f-49ef-bfc3-3d10e93505b5)
