### ISSUE TITLE
Automatically Muting All Users While Sharing Video

### ISSUE THREAD

**Issue by jtardioli** [brave/brave-talk#1156]
When sharing a video in brave talk, every time the video is played it automatically mutes everyone in the call. This seems like more of a bug than a feature to me. Would love to know how others feel about this.

**Comment by mrose17** [comment]
I talked with the Jitsi folks and they inform me:

```This is the intended behavior. As playing that video is local, there is no real sync between videos and if just one microphone is turned on it will feed the video sound in the meeting and everyone will hear the sound twice and it becomes a very unpleasant experience and hard to tell what is going on.```

So, changing the behavior would be "sub-optimal". of course, nothing prevents someone from un-muting, if they wish (assuming that the moderators allow participants to un-mute)!

**Comment by jtardioli** [comment]
Anyway we could get a toggle for this? If you are watching a movie in a large group and want everyone to be silent when the movie is playing that makes sense. However if you are trying to discuss what you are watching, it becomes very annoying to constantly unmute, people talk and don't realize they have been muted, etc.
