### ISSUE TITLE
Incorrect avatar image selected when starting Web3 call

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1157]
### Description
Incorrect avatar image selected when starting Web3 call. The issue seems to be with indexing when `Show all NFTs` is disabled

### Steps to reproduce

1.  Create a Web3 call 
2.  Select an avatar to join the call
3.  Shows/Uses a different avatar than selected one

### Actual Result

https://github.com/brave/brave-talk/assets/17010094/52b7cbdb-bfc1-48dc-b2ea-517b9c7b123c

### Expected Result
Should use the current selected one to show as the avatar without having to select Show all NFTs

### Additional Information
cc: @mrose17 @davidsuh11

**Comment by mrose17** [comment]
@srirambv - this is ready for testing on `dev2` ... thanks!

**Comment by srirambv** [comment]
This is fixed. Selecting the avatar shows the correct image when initiating the call

https://github.com/brave/brave-talk/assets/17010094/10419f40-9a90-4a2d-bc56-c2d80d91c52e
