### ISSUE TITLE
Web3 Brave Talk Send Crypto

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#1199]
Implement [Web3 Brave Talk Send Crypto](https://docs.google.com/document/d/1FyGUVg3pqW6nQNWnIvq3MKqfagy0hEgNJtPdxcdlvQ8/)

**Comment by srirambv** [comment]
Verified the following on Dev2 server on 
<table>
<th>Brave Browser<td>Premium Call</td><td>Web3 ETH Call</td><td>Web3 Solana Call</td>
</th>
<tr>
<td>Send Crypto option on Desktop</td><td> ❌ </td><td> ✅ </td><td> ❌ </td>
</tr>
<tr>
<td>Send Crypto option on Android</td><td> ❌ </td><td> ✅/ ❌ (#1245) </td><td> ❌ </td>
</tr>
<tr>
<td>Send Crypto option on iOS</td><td> ❌ </td><td> ✅ </td><td> ❌ </td>
</tr>
</table>

* Verified able to successfully select Send Crypto on platforms and send it successfully

<table>
<th>Non-Brave Browser <td>Edge</td><td>Chrome</td><td>Firefox</td>
</th>
<tr>
<td>Send Crypto option on Desktop with Wallet extension</td><td> ✅ </td><td> ✅ </td><td>  ❌  </td>
</tr>
<tr>
<td>Send Crypto option on Desktop without Wallet extension</td><td> ❌ </td><td> ❌</td><td> ❌ </td>
</tr>
<tr>
<td>Send Crypto option on Android</td><td> ❌ </td><td> ❌</td><td> ❌ </td>
</tr>
<tr>
<td>Send Crypto option on iOS</td><td> ❌ </td><td> ❌ </td><td> ❌ </td>
</tr>
</table>

* Verified able to send crypto from other browsers with extension with BAT balance

<table>
<th>Hardware Wallet <td>Ledger Nano</td><td>Trezor</td>
</th>
<tr>
<td>Send Crypto option on Desktop</td><td>  ✅  </td><td> ✅ </td>
</tr>
</table>

* Verified able to connect H/W wallet and select Send Crypto and approve transactions on h/w wallet 

-------

Encountered the following issues

- [Send Crypto icon looks disabled](https://github.com/brave/brave-talk/issues/1235)
- [Wallet connect prompt shows twice when Web3 talk link is launched](https://github.com/brave/brave-talk/issues/1236)
- [Sender should get a response if the user has rejected the transaction](https://github.com/brave/brave-talk/issues/1238)
- [Confirm transaction message is confusing ](https://github.com/brave/brave-talk/issues/1239)
- [Send transaction confirmation is not shown if wallet get locked ](https://github.com/brave/brave-talk/issues/1240)
- [Invalid amount error message has a misspelt word](https://github.com/brave/brave-talk/issues/1241)
- [Unable to join Web3 call on Android](https://github.com/brave/brave-talk/issues/1245)
- [Send Crypto message needs to be aligned for mobile view](https://github.com/brave/brave-talk/issues/1246)
- [Placeholder `[object Object]` shown on input info message](https://github.com/brave/brave-talk/issues/1247)
- [Confirm Send message should be closed when panel is shown for transaction confirmation](https://github.com/brave/brave-talk/issues/1248)
