### ISSUE TITLE
disable check for Brave browser when creating a conference room

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#1204]
On FCS, it was required that only the Brave browser could create a conference room. Disable that check, cf., https://github.com/brave/brave-talk/tree/remove-browser-browser-requirement

This is for non-premium calls. A future issue will address premium calls and web3 calls.

*NB: on iOS, Jitsi does not detect Edge and Firefox properly. They are investigating, but you should expect those tests to fail at the present time.*

**Comment by mrose17** [comment]
For testing:

On desktop (mac, windows, linux): chrome, duckduckgo, edge, firefox, opera, and vivaldi.
On iOS: chrome, duckduckgo, edge, firefox, opera (AFAIK: no vivaldi on iOS).
on Android: chrome, duckduckgo, edge, firefox, opera, vivaldi.

**Comment by srirambv** [comment]
Verified able to create Brave Talk rooms on the following browsers in Linux

Chrome ✅  | Firefox ✅  | Edge ✅  | Opera ✅ | Vivaldi ✅
-- | -- | -- | -- | --
<video src=https://github.com/brave/brave-talk/assets/17010094/7b8cda72-55f7-4568-b8a8-59cf3a79756a> | <video src=https://github.com/brave/brave-talk/assets/17010094/41f9d325-7ca6-4e81-94e4-af3c19c76cc7> | <video src=https://github.com/brave/brave-talk/assets/17010094/e1de5b4c-741e-4474-8426-522553a4a828> | <video src=https://github.com/brave/brave-talk/assets/17010094/daaa2e16-31f9-4876-a151-fc8b8f10e921> | <video src=https://github.com/brave/brave-talk/assets/17010094/7c2e40db-81c6-42f2-8272-4f57cdabc892>

Note: No DDG browser available for Linux 

-----------------------

Verified able to create Brave Talk rooms on the following browsers in Windows

Chrome ✅  | Firefox ✅  | Edge ✅  | Opera ✅ | Vivaldi ✅ | DDG ✅ 
-- | -- | -- | -- | -- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/f5b7aebe-9249-44ec-9b1b-6e0a0c0f1a1c> |  <video src=https://github.com/brave/brave-browser/assets/17010094/d32bae5a-6c67-468e-9242-e648f3ff46ac> | <video src=https://github.com/brave/brave-browser/assets/17010094/890c2779-4713-4329-8fda-7e00f9510ade> | <video src=https://github.com/brave/brave-browser/assets/17010094/a5f31800-35c1-41ba-8d18-d93a79e4088d> | <video src=https://github.com/brave/brave-browser/assets/17010094/9ece19ec-6109-46d8-aab3-a7825df16813> | <video src=https://github.com/brave/brave-talk/assets/17010094/6ab942cf-4818-4b09-acbb-76ac12c5870a>

-----------------------

Verified able to create Brave Talk rooms on the following browsers in macOS

Chrome ✅  | Firefox ✅  | Edge ✅  | Opera ✅ | Vivaldi ✅ | DDG ✅ | Safari ✅ 
-- | -- | -- | -- | -- | -- | --
<video src=https://github.com/brave/brave-talk/assets/17010094/631552b1-f1dd-43f4-a165-27feb8382ef1> | <video src=https://github.com/brave/brave-talk/assets/17010094/bc63314c-c0ae-41c3-b3d5-e270226f422c> | <video src=https://github.com/brave/brave-talk/assets/17010094/83f4b5d1-f330-4c53-9f67-d9566fe7949c> | <video src=https://github.com/brave/brave-talk/assets/17010094/72bbfe41-48c9-485a-a34a-04183c7be44c> | <video src=https://github.com/brave/brave-talk/assets/17010094/180a8228-194d-4cff-b037-0ea0b72a97b9> | <video src=https://github.com/brave/brave-talk/assets/17010094/0c18ea29-dc3d-4c3c-93fa-71adb9caa0ae> | <video src=https://github.com/brave/brave-talk/assets/17010094/462a2f30-0934-4642-9cd5-5cc7d54cf79c>

**Comment by srirambv** [comment]
Verified able to create Brave Talk rooms on the following browsers on Android 13

Chrome ✅ | Edge ✅ | FireFox ✅ | DDG ✅ | Opera ✅ | Vivaldi ✅ 
-- | -- | -- | -- | -- | --
<video src=https://github.com/brave/brave-talk/assets/17010094/05f1dc5a-ff69-45db-b513-7ef69d7c0596>| <video src=https://github.com/brave/brave-talk/assets/17010094/2e32f85a-40c9-4185-8ec8-d153edc92c53> | <video src=https://github.com/brave/brave-talk/assets/17010094/ba2b249f-2776-4c0f-b667-969a4418617a> | <video src=https://github.com/brave/brave-talk/assets/17010094/8a8521e6-2432-453a-8f74-8efeafb0b502> | <video src=https://github.com/brave/brave-talk/assets/17010094/04b3da90-6f59-4c9b-94eb-e46b23f398b3>|  <video src=https://github.com/brave/brave-talk/assets/17010094/b1b94135-6381-478d-8715-a6dc2b74fcff>

**Comment by srirambv** [comment]
Verified able to create Brave Talk rooms on the following browsers on iOS 16.5

Chrome ✅ | DDG ✅ | Opera ✅ | Safari ✅ 
-- | -- | -- | --
<video src=https://github.com/brave/brave-talk/assets/17010094/51fcc586-46de-4f5e-abb6-7a845051daa2> | <video src=https://github.com/brave/brave-talk/assets/17010094/5cde0a7f-feda-4dd5-b3ab-5f6c0514664d>|  <video src=https://github.com/brave/brave-talk/assets/17010094/a262ae6e-6c5a-4f5c-817f-c86be0dfc39b>| <video src=https://github.com/brave/brave-talk/assets/17010094/b44570a8-29f3-4822-a336-6a45e80138f3>
