### ISSUE TITLE
Do not add the address to exception/allow list from the address creating the room

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1212]
Part of https://github.com/brave/brave-talk/issues/920

### Description
Do not add the address to exception/allow list from the address creating the room

### Steps to reproduce

1. Create a Web3 talk room
2. Copy the wallet address from which you are creating the room
3. Enter the wallet address in exception list
4. Still able to create room 

### Actual Result

https://github.com/brave/brave-talk/assets/17010094/926b32b6-1657-47ab-8202-ee8de1654167

### Expected Result
Maybe check if the address is same as the one that is creating the call

### Additional Information
cc: @mrose17 @hadiamjad

**Comment by mrose17** [comment]
@hadiamjad - if the user puts their own address in either list, the website should delete it from the list before sending it to the subscription service. similarly, if the subscription service is processing the lists and sees the sender's address, they should just ignore it.

this is consistent with the token-gating approach in which whoever creates the room is always allowed to join as a participant and is always a moderator.

**Comment by srirambv** [comment]
Verified steps from issue description. Verified adding the same address creating the call into exclude/allow list, shows error message

https://github.com/brave/brave-talk/assets/17010094/6f590828-363a-4415-9be9-2cd97cf6cae8

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/brave-talk/pull/1223
