### ISSUE TITLE
Send Crypto icon looks disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1235]
### Description
Send Crypto icon looks disabled

### Steps to reproduce

1. Create a Web3 call that supports send crypto
2. Hover over the participant menu
3. Send Crypto icon is light and looks disabled 

### Actual Result

Moderator | Guest 
-- | --
![brave_qi3G89kxmQ](https://github.com/brave/brave-talk/assets/17010094/c178acc3-e274-4d10-a354-0790391c605e) | ![brave_0M51Xf6Dgh](https://github.com/brave/brave-talk/assets/17010094/84a92604-8676-4ded-a669-a41f70f6faf5)

### Expected Result
Similar to other icons

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
@aguscruiz has provided this update! to be merged soonish...
![send-crypto](https://github.com/brave/brave-talk/assets/400552/f9b20829-6e7b-4c87-a3e4-1dca3f3a0e30)

**Comment by mrose17** [comment]
@srirambv - this should be fixed on `dev2` ...

**Comment by srirambv** [comment]
This looks fixed 
![image](https://github.com/brave/brave-talk/assets/17010094/c3727688-a4b4-4203-b7ae-b0d6c543a7d0)
