### ISSUE TITLE
Wallet connect prompt shows twice when Web3 talk link is launched

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1236]
### Description
Wallet connect prompt shows twice when Web3 talk link is launched

### Steps to reproduce

1. Create a Web3 call on Dev2 server
2. Open the link in a different Brave browser
3. Connect panel is shown twice
4. Open the same link in Edge with Phantom wallet
5. Shows the connect wallet prompt multiple times

### Actual Result

https://github.com/brave/brave-talk/assets/17010094/d8fee88e-80b8-47af-b69f-6b6fae35a0a5

https://github.com/brave/brave-talk/assets/17010094/ceeb4c90-1f59-4938-abf1-779104444b8f

### Expected Result
Should only show the connect wallet once

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
@Douglashdaniel - could you help @bcaller understand what is going on here? thank you!

**Comment by mrose17** [comment]
@srirambv - can you verify this fix. it looks good to me, but i'd like an expert to take a look... thanks!

**Comment by srirambv** [comment]
@mrose17 I can still repro the issue on staging. 

https://github.com/user-attachments/assets/5dfd7d1c-bb3f-4568-a511-4717846a4c0c

**Comment by bcaller** [comment]
Is staging properly deployed from the main branch? Looks like it might not be.

**Comment by srirambv** [comment]
@bcaller @mrose17 I can still reproduce the double popup on talk.bravesoftware.com as well 

https://github.com/user-attachments/assets/8ff674ea-fd2e-4542-b119-12a1fe84d8cc

**Comment by bcaller** [comment]
Thanks, I see that while ETH was fixed, I neglected to fix Solana

**Comment by srirambv** [comment]
Looks fixed now 

https://github.com/user-attachments/assets/94f3f14a-ce89-42b9-9542-b44488375c88
