### ISSUE TITLE
Unable to join Web3 call on Android 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1245]
### Description
Unable to join Web3 call on Android 

### Steps to reproduce

1. Create a Web3 call in Dev2 that supports Send Crypto
2. Try to join the call from Android
3. Fails to join with error signing message

### Actual Result

https://github.com/brave/brave-talk/assets/17010094/bdf26c8d-c185-4380-9db7-752a2904798b

### Expected Result
Should be able to join the call without issues 

### Additional Information
cc: @mrose17

**Comment by srirambv** [comment]
Tried it again on Beta and was able to join the call. Did encounter #1246 on Android as well

https://github.com/brave/brave-talk/assets/17010094/e2dc80e4-3010-458b-9f00-c9f8f03dc2f7

**Comment by mrose17** [comment]
So, if https://github.com/brave/brave-talk/issues/1246 is fixed, is this still an issue?

**Comment by srirambv** [comment]
#1246 is independent of this one. I will check this once again on Release/Beta/Nightly builds on Android. If its working fine will close it else we'll need to investigate whats going on

**Comment by mrose17** [comment]
Thank you!

**Comment by mrose17** [comment]
@srirambv - may i impose on you to take another look? (i think that some other android fixes a while back may have addressed this issue too.) thanks!

**Comment by srirambv** [comment]
Verified and able to join the call on dev2.talk.brave.software without any issue
