### ISSUE TITLE
Placeholder `[object Object]` shown on input info message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1247]
### Description
Placeholder `[object Object]` shown on input info message

### Steps to reproduce

1. Create a Premium call on Dev/Dev2 server
2. Try to join the call from an iPhone/iPad
3. Shows message about input that has placeholder text

### Actual Result
<img width=400 src=https://github.com/brave/brave-talk/assets/17010094/cb98fabf-78d3-4e95-8a5a-341b6c8d66d1>

### Expected Result
No placeholder text in message

### Additional Information
Note: this is Brave Talk issue and happens on Web3 calls as well
cc: @mrose17

**Comment by horymury** [comment]
This was addressed in the linked PR- will be deployed with the next release.

**Comment by mrose17** [comment]
@horymury - Thank you!

**Comment by saghul** [comment]
This has been addressed and deployed already, you can close this.
