### ISSUE TITLE
Unable to load NFTs/POAP when trying to expand NFT section for Avatar selection

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1252]
### Description
Unable to load NFTs/POAP when trying to expand NFT section for Avatar selection

### Steps to reproduce

1. Create a Web3 talk call
2. Open console
3. Throws error and doesn't show NFTs/POAPs

### Actual Result
![image](https://github.com/brave/brave-talk/assets/17010094/96312b7b-c87e-4331-9aca-e6b0cd7cb6a3)

### Expected Result
Shows NFTs/POAPs

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
It turns out that talk.brave.software is broken! we're doing some reconfiguration on it... once it's back up, i'll test it and then close the issue...

**Comment by mrose17** [comment]
@srirambv -`dev3` is broken, but talk.brave.software is back, please try it out...

**Comment by mrose17** [comment]
@srirambv - it should be fixed and production. Please take a look!

**Comment by srirambv** [comment]
Verified on both `https://talk.brave.com` and `https://talk.brave.software` and working fine. Able to list all NFTs/POAPs

Dev Server | Production
-- | --
<img width=300 src=https://github.com/brave/brave-talk/assets/17010094/179f388c-798a-4de0-a81a-9b76555b4fc2> | <img width=300 src=https://github.com/brave/brave-talk/assets/17010094/62839542-f952-4cf8-9bfb-97acc576885d>

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/brave-talk/pull/1265
