### ISSUE TITLE
Log-in loads 8x8 SSO page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#1307]
### Description: 
Log-in loads 8x8 SSO page

### Steps to Reproduce 
  1. Open Brave and select Talk from menu
  2. Create a free call
  3. Open call menu and go to setting
  4. Tap on Name
  5. Tap on `Log-in` on top right corner, opens 8x8 SSO page

### Actual result: 

https://github.com/brave/brave-talk/assets/17010094/7fe567ec-842f-4bf2-8091-db78e0d7ba36

### Expected result:
No 8x8 login shown on profile

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 
All

### Device details: 
iPad (iOS 16.7.2)

### Additional Information
This is iOS only issue for Brave Talk. Android works similar to Desktop just shows the profile name and no `Log-in` button is shown
cc: @iccub @mrose17

**Comment by mrose17** [comment]
@srirambv - github appears to have lost the video above.

Regardless, this was fixed in the website version, but the current SDK doesn't have the fix, e.g.,
![IMG_0590](https://github.com/brave/brave-talk/assets/400552/dabed1bb-87dc-429b-9586-c6b64a0b236a)

@saghul - could this fix be scheduled for the next SDK release? Thank you!

**Comment by saghul** [comment]
Will do.

**Comment by saghul** [comment]
This will be part of SDK 8.6.1, we are hiding the Login option.

**Comment by mrose17** [comment]
Great! I will add the `blocked` label, and we will QA it after we have a TestFlight version with the new SDK!

**Comment by saghul** [comment]
Small correction, the version with the fix is 8.6.2, released today.

**Comment by mrose17** [comment]
@srirambv - grab a copy of `0.0 (24.1.19.16)` and try it out... thanks!

**Comment by srirambv** [comment]
Verified no Login option in profile details page

https://github.com/brave/brave-talk/assets/17010094/2d759646-15a8-4e2a-a5e8-7ee2e1f6740d
