### ISSUE TITLE
Brave talk call full with only two people?

### ISSUE THREAD

**Issue by johnmarco123** [brave/brave-talk#1339]
I use brave talk for more then 4 hours nearly every day and noticed that there are times where with only two people in a call the call will say that it is full when attempting to join. Sometimes with even 1 person in the call i cant join. Sometimes even with 0 people in the call it says the link is full and i cannot join. I'm unsure the cause of this, maybe there is still some data saying there is users on even though there isnt...? We usually use the same brave link and have had to switch it a few times because of this issue.

**Comment by mrose17** [comment]
I suspect that this is a dup of #1333 ... we're planning to take a look at that next week.
