### ISSUE TITLE
Add a "Leo" button to the toolbar

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#1392]
Add a "Leo" button to the toolbar. It should appear only for premium moderators. The button has two states: "on" and "off", which reflects whether transcription is on/off. The button toggles the transcription status. Note that this should not observe/interfere with A/V recording.

When a user (other than the moderator) gets their first transcript chunk, if they are using the Brave browser, use the Jitsi notification UI to tell the user that they can use Leo to analyze the meeting.

@minkyeongshin to provide the icon for the Leo button (based on what the Jitsi API expects).
@rmcfadden3 to provide exact wording on notification.

@bcaller - note that to detect the current state of recording, the site should listen for the `recordingStatusChanged` event.

**Comment by rmcfadden3** [comment]
@minkyeongshin — can you drop a screenshot of your design mock once it's ready? That way I'll know how much real estate I have to work with, in terms of character count.

**Comment by mrose17** [comment]
sorry for the confusion:  at the present time, the design "ask" is only for an icon to go in the toolbar:
![Screenshot 2024-04-05 at 08 15 51](https://github.com/brave/brave-talk/assets/400552/eefaf4ef-338e-4979-a9c9-85a338d59e89)
initially, we're planning to use the Jitsi [showNotification](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands#shownotification) API call. so you can have a "reasonable" amount of text (say up to 300 characters).

**Comment by bcaller** [comment]
Is this actually possible with the JAAS API? https://developer.8x8.com/jaas/docs/customize-ui-buttons links to  [list of button names](https://github.com/jitsi/jitsi-meet/blob/a76f9d548b2cfceaf335250867b88a41667107e0/config.js#L782-L826)

**Comment by bcaller** [comment]
Well we can brand the default icons as described at https://developer.8x8.com/jaas/docs/jaas-prefs-advanced-branding#branding-data-payload - but are we able to create a new icon or do we have to be sneaky and misuse an existing icon?

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/blob/a76f9d548b2cfceaf335250867b88a41667107e0/config.js#L949

You can use a data URL or any URL to an icon.

**Comment by mrose17** [comment]
Thanks. Please remind me: what handler triggers when a button is pressed (presumably indexed by `id`)... sorry for not knowing this stuff better by now...

**Comment by saghul** [comment]
Here you go! https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events#toolbarbuttonclicked

**Comment by mrose17** [comment]
Thank you!

**Comment by bcaller** [comment]
I see, I was looking at the wrong documentation (developer.8x8.com rather than jitsi.github.io) and there is in fact a [customToolbarButtons](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration#customtoolbarbuttons) config option.

**Comment by bcaller** [comment]
OK I managed to add Leo to `customToolbarButtons` and `buttonsWithNotifyClick` and added an event handler.

<img width="702" alt="image" src="https://github.com/brave/brave-talk/assets/5838651/eede92af-6f3e-44da-adfa-6b2f64273884">

But the button only appears in the toolbar menu rather than the main toolbar. I'm not yet sure how to customise which buttons appear at the bottom of the screen.

**Comment by bcaller** [comment]
OK, I think some config can be done via `executeCommand('overwriteConfig',{toolbarButtons: [`. But where do we specify the initial order of microphone, camera, desktop, chat, raisehand... is that just the default?

https://github.com/jitsi/jitsi-meet/blob/a76f9d548b2cfceaf335250867b88a41667107e0/config.js#L787-L789

```
// Notes:
// - it's impossible to choose which buttons go in the "More actions" menu
// - it's impossible to control the placement of buttons
```

**Comment by bcaller** [comment]
Ah OK the order is defined here: https://github.com/jitsi/jitsi-meet/blob/b54cec8d77fee77218378532bfac665e75289f90/react/features/toolbox/functions.web.ts#L410-L442

So the Leo icon will always be at the end of the "More Actions" menu and we can't move it without either:
* removing a lot of buttons like in the screenshot above
* or replacing a load of inbuilt buttons with custom versions. This wouldn't work for the `raisehand` or `reactions`, but we could place the Leo button at the end of the main toolbar.

Overall, probably worth just starting with it at the end of the More Actions menu.

**Comment by mrose17** [comment]
Just to clarify, the button should appear for `context.user.moderator === true && context.features.transcription === true`

**Comment by bcaller** [comment]
Current state: 
<img width="644" alt="image" src="https://github.com/brave/brave-talk/assets/5838651/6b2833a6-2dc9-4b00-8b3d-41bf2cff091b">
I don't believe there is currently a way to move the button onto the main bar.

I was able to get the following:
<img width="644" alt="image" src="https://github.com/brave/brave-talk/assets/5838651/e20a749c-8f59-4092-83b5-96ec9cfe5984">
Only by deleting all the toolbar buttons which appear in More Actions. Since we need those buttons, we have a problem.

**Comment by saghul** [comment]
Sorry I mislead you. I can confirm this is not currenrly possible. We'll work on making it possible.

**Comment by mrose17** [comment]
@saghul - Understood. Thanks for working on it.

**Comment by mrose17** [comment]
Fixed in https://github.com/brave/brave-talk/pull/1472
