### ISSUE TITLE
Add status line to talk.brave.com to give notices on system outages, etc.

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#14]
The question is where to get the data from...

**Comment by tackley** [comment]
Option 1 seems sensible to me. To implement, we'll need to:

- update the CSP to include `https://status.brave.com` as a `connect-src` - this appears to have already been done
- implement the code to read the status json and if brave talk is non-operational display a banner.

**Comment by mrose17** [comment]
@tackley - i confirm option 1.

**Comment by stephendonner** [comment]
Verified `PASSED` on dev (and staging).

Confirmed link to (Brave's) `Service Status` (`https://status.brave.com/`) appears at the bottom right of the footer, on `https://talk.brave.software/` and `https://talk.bravesoftware.com`:

<img width="1312" alt="Screen Shot 2022-06-10 at 8 19 37 AM" src="https://user-images.githubusercontent.com/387249/173097757-855cc200-684b-49cf-914e-77834c7710ab.png">
