### ISSUE TITLE
Change text on home page

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#1404]
This issue is created, but shouldn't be deployed until marketing confirms.

From:

        Trial brings 30 days of free access to Brave Talk Premium. After 30 days, the credit card you enter will be charged $7.00 US per month. Cancel any time.

To:

        Trial brings 7 days of free access to Brave Talk Premium. After 7 days, the credit card you enter will be charged $7.00 US per month. Cancel any time.

**Comment by mattmcalister** [comment]
we also need the account site and back end subscriptions services to be updated prior to releasing this change on the Brave Talk site. see spec https://docs.google.com/document/d/1OBoIrVp8kIieQ8JhpowPrhNqvLojOjMnHRD8ay_lLmA/edit?usp=sharing
