### ISSUE TITLE
[Feature request] Whiteboard with real-time collaboration and E2EE

### ISSUE THREAD

**Issue by ElsAr4e** [brave/brave-talk#1426]
It would be great if you were able to have a whiteboard (with E2EE by default) that allows real-time collaboration like for example Excalidraw: https://github.com/excalidraw/excalidraw

But you should be also able to share pdfs so you and other participants can annotate PDF files - with tools like a pen (different colors and sizes) and a ruler ( that uses OpenBoard (https://github.com/OpenBoard-org/OpenBoard)); maybe it's also possible to convert handwriting to text like Nebo.

And maybe you can have different permissions so that for example only admins can delete pages and some participants can only view the whiteboard.

**Comment by mrose17** [comment]
This is a great idea, but out of scope for this project. I undertand that the Jitsi folks are working on something like this, and when it merges into Jitsi-as-a-Service (JAAS), it is likely to be supported by Brave Talk. So, my guess is that the best place for this request is https://github.com/jitsi/jitsi-meet/issues

Thank you!
