### ISSUE TITLE
Improve data available for product analysis

### ISSUE THREAD

**Issue by tackley** [brave/brave-talk#15]
We have very limited visibility of talk product usage currently, making it difficult to prioritise product changes. This issue proposes improvements to stats collection, with the aim of carefully ensuring we do not break user's privacy.

## Current

Currently the subscriptions service logs and presents to metabase each time a room is created, with the following data:

| Column | Description |
| ---- | ---- |
| name | the room name |
| tier | paid (for subscribers) or free (for 1:1 calls) |
| head_count | the number of JWT's issued to allow entry to the room (incremented every time a new JWT is issued) |
| created_at | when the room was initially created |

Note head_count represents the total number of people who have been issued a token to enter the room. So a weekly meeting of 60 people would present a head count of 60*4 = 240 over a typical month. 

## Limitations

Two particular cases make analysis difficult currently:

1.  *scheduled use rooms*.  e.g. the same room used for weekly meetings. We know when the room was created; but if that room was used on an ongoing basis for e.g. weekly team meetings, we do not have records of that. We therefore have no visibility on the popularity of this use case; nor on how much this contributes to overall usage. Also, 8x8 will include this in the monthly active user counts, which we cannot cross check.
2. *single person rooms*. 8x8 apparently do not charge us for rooms that are created, but only have a single person (the creator) join. Our own MAU stats does not take this into account, causing a discrepancy.

## Proposal

This issue proposes that in addition to the above we log and present to metabase each time we issue a token for entry to a room:

| Column | Description | 
| ---- | --- |
| room_identifier | a unique identifier derived from the room_name e.g. `hash(room_name + nonce)` |
| timestamp | when the event happened |
| event | "created" - the room was created; "joined" - a ticket to join the room was issued; "moderator-renew" - a renewal of the moderator ticket was issued |
| new_mau | true or false: was this use flagged to 8x8 as a new monthly active user? |
| tier | paid (for subscribers) or free (for 1:1 calls) - only populated on "created" events |

No additional data is stored against these events, just those four fields. In particular there is no link to the user, the subscriber or user agent.

With this data, we can better understand long term usage of rooms, and better predict our cost base - addressing both of the limitations noted above. 

This approach will be subject to privacy review before implementation.

**Comment by thypon** [comment]
What's the status for this issue?

**Comment by mrose17** [comment]
I like this plan. Let's start at 3 months and we can always drop it to two. This should give us a good balance!

**Comment by kdenhartog** [comment]
How is the `room_name` provided? My theoretical concern with this design is that if the `room_name` is user controlled two unique users could select a common room name such as `test` and it would throw off the metrics here if they're generated with the same salt in use.

**Comment by mrose17** [comment]
Room names are generated algorithmically by the client to have 256-bits of pseudo-entropy; however, as long as the name conforms to the syntax (43 characters, base64), it will be accepted by the system. we purposefully decided not to facilitate "vanity names", though a few of us old-timers use them.

so, it's possible to have collisions, but probably not worth worrying about.

**Comment by kdenhartog** [comment]
Sounds good, I don't see any issue with this approach.

**Comment by mrose17** [comment]
Closed as the goals can not be easily realized given the privacy concerns.
