### ISSUE TITLE
Start free call (up to 4 people)` CTA button is blank on `iOS18` device

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#1511]
### Description: 

The `Start free call (up to 4 people)` CTA button is blank on an `iOS 18` device.

### Steps to Reproduce 
  1. Launch Brave on an `iOS 18` device
  2. Go to `talk.brave.com` > *Observe*

### Actual result: 

The `Start free call (up to 4 people)` CTA button is blank on an `iOS 18` device.

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/549671b2-95f2-4107-862f-3e0846fe0d79) | ![2](https://github.com/user-attachments/assets/1705872d-87cf-4191-91f8-e1160a8a11d0) |

### Expected result:

The `Start free call (up to 4 people)` CTA button must not be blank.

|1|2|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/99d04524-f97e-49d6-8f05-6ba2c2b8e70d) | ![2](https://github.com/user-attachments/assets/f0f50093-aa9f-40ac-ab7d-256daeb88314) |

### Reproduces how often: [Easily reproduced, Intermittent Issue]

`Easily reproduced`

### Brave Version: 

```
Brave build: 1.70 (123)
BraveCore: 1.70.123 (129.0.6668.89)
Jetsi SDK: 10.1.2
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES. Jetsi SDK 9.2.2

### Device details: 

```
Device/OS: iPad Mni (6th gen) / iPadOS 18
```

### Website problems only:
- did you check with Brave Shields down? YES
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

cc: @hffvld

**Comment by mrose17** [comment]
@hffvld - I don't have an iOS 18 device here. I'm some others to try to see what's going on.

Could you one run test for me? If you tap the button, does it start a call? I'm just trying to determine whether the extent of the issue is limited to display or also functional. Thank you!

**Comment by kylehickinson** [comment]
Culprit seems to be `backdrop-filter` css

If I set add a `backdrop-filter: none` override it renders correctly

These two styles are applied to the button:

```
-webkit-backdrop-filter: blur(16px);
backdrop-filter: blur(16px);
```

Apparently iOS 18 adds full support for backdrop-filter so probably a bug with Apple’s implementation. Or there’s something weird on iOS 18 if you include the `-webkit` prefixed one as well

**Comment by mrose17** [comment]
It sounds like the best fix is to add `backdrop-filter: none;` and not worry about trying to do something "clever". wdyt?

**Comment by mrose17** [comment]
Scheduled for production on monday.

**Comment by mrose17** [comment]
Now in production! Please take a look.
