### ISSUE TITLE
Talk should refresh periodically when sitting on the home page

### ISSUE THREAD

**Issue by tackley** [brave/brave-talk#162]
On e.g. conference room systems used just for Brave Talk, the home page may remain displayed for many hours.

If there are recordings, this will continue to show long-expired recording links. It also may potentially be using an old version of the brave talk code.

When sitting on the home page for a long time, Talk should periodically refresh - perhaps a multi-hour http meta refresh would be sufficient, although this might interrupt calls which would not be desirable.

Thanks to @bradleyrichter for the report.

**Comment by mrose17** [comment]
@tackley - are there any calls going on in the background on the home page? i don't think so. what am i missing? (probably a lot!)

**Comment by tackley** [comment]
The html and javascript of the home page is loaded even while a call is in progress, though the entire screen is taken over with a full screen jitsi iframe. 

My normal "quick fix" to this kind of issue is to add something like:

    <meta http-equiv="refresh" content="14400">

to the header of the html, which instructs the browser to reload the page every 4 hours ([MDN link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta)). Javascript-free and "just works".

But in Talk's case I don't think this is approach is suitable, as we definitely don't want this to happen while the full-screen iframe is active. So instead I'd suggest we:

- add a one-hour `setTimeout` as our javascript loads
- in the callback, if a call is in progress do nothing, otherwise `window.location.reload()`

**Comment by mrose17** [comment]
It is good to check to see if a conference is in progress. However, I think that an hour is too long. May I suggest every five minutes?

The alternative is to look at whatever recordings are available and adjust the time out based on the oldest recording. That does sound like a lot more work rather than just changing a constant…

**Comment by tackley** [comment]
Refreshing the list of available recordings every 5 minutes would be fine - we should be able to implement that entirely within https://github.com/brave/brave-talk/blob/0441b6b87bb3fc73efa322094bb7c258254a71ce/src/recordings-ui.tsx.

I'd like a longer-cycle full-page refresh though too, to avoid the problem that a screen left open on the home page would potentially using an old version of the code.

**Comment by mrose17** [comment]
I agree that a dual timing approach is good:
- no updates when a confab is open
- otherwise:
  - every 5 minutes, update the `<div/>` containing the recordings
  - every 24 hours, refresh the page

how does that sound?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)



### Case One: no refreshes during meeting
* loaded `talk.brave.software`
* started a meeting (as moderator)
* joined with another participant

#### Confirmed, at 5-minute mark, meeting intact (no forced reload)

...confirmed, at 24-hour mark, meeting intact (no forced reload)

### Case Two: refresh recording page every 5 min
* loaded `talk.brave.software`
* started a meeting (as moderator)
* started recording
* waited 2 minutes
* ended recording
* sat on recordings-listing page

#### Confirmed (1st) recent-recording link appeared
* (continued)
* waited 5 minutes
* started another meeting (as moderator)
* started another recording
* waited 2 minutes
* ended recording
* (I repeated this a couple times)
* waited on recordings-listing page for 5 minutes

* Confirmed 2nd recording link dynamically appeared on `talk.brave.software`
* Confirmed via the `Console` panel in Developer Tools the `recordings` array was increased by `1`, for two total recordings

single recording | 2nd recording
-----------------|---------------
<img width="1312" alt="Screen Shot 2022-05-27 at 10 08 56 AM" src="https://user-images.githubusercontent.com/387249/170760625-9f818903-698a-4275-946e-43e608523d0d.png"> | <img width="1680" alt="Screen Shot 2022-05-27 at 10 23 14 AM" src="https://user-images.githubusercontent.com/387249/170760701-99f25cb8-2f30-4d33-9d67-71ada6f00683.png">






### Case Three: refresh page every 24 hours

* loaded `talk.brave.software`
* opened the Developer Tools panel
* chose `Console` and clear it
* advanced system clock by 23+ (but less than 24) hours
* waited for the remainder

...confirm you see an automatic reload of `talk.brave.software` via the console

**Comment by stephendonner** [comment]
Fixed by https://github.com/brave/brave-talk/pull/298; verification notes, above 👍 

Closing.

**Comment by mrose17** [comment]
Re-opening until we have a deploy next week...
