### ISSUE TITLE
Brave Talk intermittently spinning when on Brave

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-talk#179]
I can't repro this now but I've run into this twice now so figured I would file an issue and update it if it happens again. 

Every now and then Brave Talk spins indefinitely for me i.e. I would go to a room and it would be stuck in a loading phase. This has happened on both Brave Nightly and Stable. Unfortunately I forgot to capture a screenshot + console log, I'll come back and update this issue if it happens again.

@fmarier mentioned that this might happen if I'm on Secure DNS + on VPN.

cc @mrose17

**Comment by mrose17** [comment]
@stephendonner - has anyone ever reported this. do we have any STR? thanks!

**Comment by stephendonner** [comment]
> @stephendonner - has anyone ever reported this. do we have any STR? thanks!

Not to my knowledge, and certainly not recently; I can try Secure DNS + VPN on Windows/Mac for a bit, later today/early tomorrow.

**Comment by mrose17** [comment]
@stephendonner - many thanks!

**Comment by fmarier** [comment]
@wknapik  mentioned the incompatibility between DoH and our VPN on Slack today: https://bravesoftware.slack.com/archives/C08Q08M6F/p1644939002286069

**Comment by wknapik** [comment]
https://bravesoftware.slack.com/archives/C61QQMWS3/p1645008939033529?thread_ts=1645008866.861659&cid=C61QQMWS3

**Comment by tackley** [comment]
@ShivanKaul do you know which spinner are you stuck on precisely? Does the screen read "Loading..." (i.e. it's attempting to validate your subscription) or "Locating Meeting Room..." (i.e. it's now trying to obtain access credentials for the room)?

Also do you by any chance have the browser console logs or network request logs?

**Comment by ShivanKaul** [comment]
It was on the first screen, checking subscription status.

It just occurred to me that perhaps this was caused by my playing around with the Block Scripts option while testing Shields. Sure enough, if I switch on Block Scripts in Shields for talk.brave.com then I get the spinning screen. 

Apologies for the noise folks, I'll close this out, I don't think it's reasonable to expect talk.brave.com without JS enabled and that's probably what was happening. I guess it might be good to detect that a user is blocking JS (given that it's a first-class option in our Shields UI) and fail softly like for e.g. Google Docs does.

**Comment by mrose17** [comment]
I've opened an issue.
