### ISSUE TITLE
Disable the "Trying to speak? You are muted." notification

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#183]
This can be done only globally.
![136571225-3df577ef-ec51-40c6-bf44-a0b9c0403de9](https://user-images.githubusercontent.com/400552/154335057-3aada021-bfaa-4385-b4b4-f8e59b5604df.png)

**Comment by mrose17** [comment]
Development testing on https://github.com/brave/brave-talk/pull/182

**Comment by stephendonner** [comment]
Verified `PASSED` on `talk.brave.software`.  Can easily reproduce issue on `talk.brave.com` and `talk.bravesoftware.com` 👍 

Steps:
1. new profile
2. launch Brave
3. load `talk.brave.software`
4. click on `Start free call (up to 4 people)`
5. click `Allow` on the mic-permissions prompt
6. enter a name
7. click `Join meeting`
8. you're `muted` by default
9. unmute and speak
10. now mute and speak

Confirmed no more `Trying to speak?...` popups.

`talk.brave.com` | `talk.bravesoftware.com` | `talk.brave.software`
-----------------|--------------------------|----------------------
![talk brave com](https://user-images.githubusercontent.com/387249/154493620-46909478-93c4-48e3-84d0-1f79e71608d7.png) | ![talk bravesoftware](https://user-images.githubusercontent.com/387249/154493699-8cff7868-d840-4fdc-ba0c-ac8d7260aead.png) | ![talk brave software](https://user-images.githubusercontent.com/387249/154493725-05e35792-be0e-479d-ae97-40f80d787a4f.png)

**Comment by mrose17** [comment]
Fixed by #191
