### ISSUE TITLE
update copyright year in footer for premium pages

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-talk#188]
![image](https://user-images.githubusercontent.com/13509546/154543938-64aa19f6-e343-423c-9acd-cd02405f0aaf.png)

**Comment by stephendonner** [comment]
This was taken care of by @AlanBreck after @MadhaviSeelam also reported it; Jacob, have the commit handy?

**Comment by stephendonner** [comment]
> [brave/account-brave-com@0c32252](https://github.com/brave/account-brave-com/commit/0c32252e3dee39564ba753731eb94f7653352ca4)

Fixed by the above; closing.
