### ISSUE TITLE
Add "create a link for later" button

### ISSUE THREAD

**Issue by tackley** [brave/brave-talk#19]
On the brave talk home page, in addition to the "start a call" button add a "create a link for later" button.

This should:
- generate a room url
- create the room and store the moderator & refresh token in localStorage
- copy the room url to the clipboard (and display it).

I.e. all the same steps as actually creating the room, but instead of opening the call it copies the url to the clipboard.

**Comment by tackley** [comment]
Note: due to https://bugs.webkit.org/show_bug.cgi?id=222262 where webkit has quite different rules to chromium as to how to detect that it's ok to write to the clipboard - this is supported for subscribers on all platforms *except iOS* for now.

**Comment by stephendonner** [comment]
Verified `PASSED` on `https://talk.brave.software`, using a Google Pixel XL, running Android 9.0.

Steps:
1. new profile
2. launched Brave
3. loaded `talk.brave.software`
4. logged in via usual Premium flow (email confirmation)
5. confirmed the addition of the `Create room for later` button
6. clicked on the `Create room for later` button
7. confirmed it created a new room URL: `https://talk.brave.software/hLXbUng0c1GNrsc_S58MLY1uWc9VU3tEzn8kslq4Le8` and copied it to my system clipboard
8. pasted the above
9. confirmed it loaded the pre-join screen


https://user-images.githubusercontent.com/387249/144058287-8f90f00c-aed4-4cad-9091-1e24eb40f6e2.mp4

**Comment by stephendonner** [comment]
Also tested & verified the same for desktop, on macOS, using `release` and `nightly` Brave.
