### ISSUE TITLE
Add recording links to Brave Talk

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#20]
How things work right now:
- when a recording starts/stops, all participants receive an audio warning (e.g., "Recording is on"). In addition, the red REC indicator is visible at the top of the window whenever recording is occurring.
- when the moderator starts a recording, the moderator gets a notification with a "Copy Link" to allow the moderator to down the link a few minutes after the recording has been stopped by the moderator (or all attendees have left the room).
- recordings are no longer available 24h after the recording ends.

API changes:
- the `recordingStatusChange` event is sent to all participants when a recording/stops starts, i.e., `{ "on": true, "mode": "file" }` or `{ "on": false, "mode": "file" }`
- the `recordingLinkAvailable` event is sent only to the moderator when recording starts, e.g., `{ link: "https://..." }`
- a new URL -- `https://api-vo.jitsi.net/jaas-recordings/link/details?url={{URL}}`--  is available to return `{ expiresAt: ... }`

Site changes (for moderator only):
- the recording URL along with room name, creation and expiration timestamps are stored in `localStorage`, and entries are automatically pruned as they expire.
- when the site loads, this information is displayed to the user allowing them to download the files.
- the new URL is not used in this implementation.

here is a sample from the development site. (note that the styling isn't done...)
<img width="1532" alt="Screen Shot 2021-11-22 at 12 19 25" src="https://user-images.githubusercontent.com/400552/142925324-3c6a885d-6cd9-4798-8068-16c7a4b54e80.png">
-

**Comment by tackley** [comment]
Release to production in #110 

![Screenshot 2022-01-03 at 16 35 17](https://user-images.githubusercontent.com/51444/147956998-3ee6be98-33b9-4178-a9b4-5c0326e0e227.png)
