### ISSUE TITLE
Have dev/staging use separate JAAS accounts for webhooks and branding develop/testing

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#229]
res ipsa loquitur

**Comment by tackley** [comment]
The github action build process already passes an environment variable to webpack indicating which environment it is building for, see e.g. its use [here](https://github.com/brave/brave-talk/blob/main/src/index.ts#L48).

So likely the main change here is to derive the vpass [here](https://github.com/brave/brave-talk/blob/main/src/index.ts#L29) to the correct value based on that environment variable.
