### ISSUE TITLE
Investigate talk.brave.com layout on iPhone SE 1st gen

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#232]
cf., https://community.brave.com/t/display-issues-with-mobile-client-running-on-older-iphone-se-1st-gen/364269

i can't figure out where some of the text and images are coming from. it is rather odd.

**Comment by btlechowski** [comment]
Looks good on:
iOS 15.2
Brave 1.37 (22.4.4.22)
Device: iphone SE (1st)

![IMG_0083](https://user-images.githubusercontent.com/34715963/161765454-2a46745c-db6a-4845-a7eb-46b3ade56024.PNG)
![IMG_0084](https://user-images.githubusercontent.com/34715963/161765461-486129ef-76e3-4b90-89ce-2f79b763ff7b.PNG)
![IMG_0085](https://user-images.githubusercontent.com/34715963/161765463-03891d9d-271f-426d-a8ff-25dac83af26d.PNG)
![IMG_0086](https://user-images.githubusercontent.com/34715963/161765465-e0963220-e9eb-449c-907e-3a59d02f3856.PNG)
![IMG_0087](https://user-images.githubusercontent.com/34715963/161765467-4c868e11-348e-4bd4-95ed-fe8b90075b83.PNG)
![IMG_0088](https://user-images.githubusercontent.com/34715963/161765469-adcbc0b8-4a49-4cd0-a9ab-6baea15e87ca.PNG)
![IMG_0089](https://user-images.githubusercontent.com/34715963/161765470-ee746bf6-18aa-4968-8190-27a5750a0e26.PNG)
![IMG_0090](https://user-images.githubusercontent.com/34715963/161765472-f678df13-4def-4ed1-bf4d-0f67ad574a2a.PNG)
![IMG_0091](https://user-images.githubusercontent.com/34715963/161765474-a127d67e-4f6d-4695-8d0a-f5ee7fbb9df6.PNG)
![IMG_0092](https://user-images.githubusercontent.com/34715963/161765476-54cfddc0-dcaf-4e92-b6ab-660c38f817e7.PNG)

**Comment by btlechowski** [comment]
Looks good on:
iOS 15.2
Safari
Device: iphone SE (1st)

![IMG_0093](https://user-images.githubusercontent.com/34715963/161768344-46ee1586-d80f-4454-be28-32af6f8bf36f.PNG)
![IMG_0095](https://user-images.githubusercontent.com/34715963/161768353-65d452df-55a3-49bf-84fc-503c0ae01370.PNG)

**Comment by mrose17** [comment]
Issue reported is likely due to a safari extension. As the screenshots above show, on both the Brave Browser and Safari, the page renders correctly.
