### ISSUE TITLE
Allow vanity Brave Talk URLs

### ISSUE THREAD

**Issue by pes10k** [brave/brave-talk#6]
These would be valuable even if they were limited to intra-brave conversations

so something like talk.brave.com/@pes10k

from brave/brave-together#183: Provide subscribed users to create a custom URL that can be shortened and shared for calls. Current implementation has a big alphanumeric value after domain which is not easy to remember or spell out. Can make the feature a premium option and allow user customization for future.

an additional feature would be to automate the save-as-shortcut functionality when creating a vanity confab url

**Comment by mrose17** [comment]
Closing the issue since the "negatives" appear to outweigh the "positives".

**Instead, if you'd like personalized meeting room names, please use a URL shortening service or put in a redirect at your website.**

The use of personalized meeting room names reduces entropy making it easier to guess names, and the only effective way to combat that is with (mandatory) passcodes.

Thank you for your patience as this issue was considered!

**Comment by mrose17** [comment]
cc: @pes10k

**Comment by pes10k** [comment]
> Instead, if you'd like personalized meeting room names, please use a URL shortening service or put in a redirect at your website.

This works fine mostly (its what I do) but im worried then that others will use my "vanity URL" talk room when I'm not using it (and so i might schedule a call with someone at the URL / room, only to find some unrelated rando's are using it when I join).

Are there plans for a "only allow this room to work when the creator is in the room" option?  If so, then i think the above approach would work well.

I appreciate that rando's could already be in my Brave Talk room with a BT-assigned vanity URL.  The only difference is that if i use a link shortener service, i have to share the URL with folks unrelated to the calls I want to make (i.e., the shortener service), and so somewhat more likely that rando's will come across it

**Comment by mrose17** [comment]
One aspect of the architecture is that a conference room has zero state when no one is there. The thing which is stateful are the JWTs that are stored in the browser's `localStorage`. That is all on purpose, as it's effectively necessary to maintain the privacy and security goals we have for Brave Talk.

This is complicated by the nature of the non-moderator JWTs, which have a short, but non-zero expiration time.
