### ISSUE TITLE
Easily find Brave Talk tab - icon in top level Brave UI

### ISSUE THREAD

**Issue by bbondy** [brave/brave-talk#7]
It would be great to have some kind of an icon that only appears on top level UI when a Talk session is active.  The button would go back to a Brave talk video.  I find I sometimes lose the tab too easily because it’s mixed with other tabs. I wouldn’t want the button there when no Talk session is active though.

Perhaps using a different task bar icon is another possibility.

I think the media icon might be the best place to put it where playing videos go.

**Comment by mrose17** [comment]
To be addressed by the Brave Talk sidebar button under discussion.
