### ISSUE TITLE
Turn down logging client side

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-talk#749]
It appears that we're logging some things that don't need to be logged such as the JWT token stored in the local storage and some erranious `TimeLimitedCredential` which aren't normally supposed to be logged. If you want examples of the data I was seeing in my console, check out this slack message (https://bravesoftware.slack.com/archives/C021S0FN3V1/p1678981705173359). I don't want to post the specific information here publicly since at least the JWT is sensitive.

Some of this information may have been appearing if people were using developer builds to access the call though, so we should double check if this is something unique to when @mrose17 @tackley and @johnhalbert were on a call or if this is actually information that's being leaked in production.

**Comment by tackley** [comment]
It wasn't just because we were on the call - this is standard behaviour.

**Comment by kdenhartog** [comment]
Ok, these look to be security sensitive so we should at least limit the logging of this information so we're not unnecessarily exposing sensitive information.
