### ISSUE TITLE
Warn user before closing window/browser if active Talk session

### ISSUE THREAD

**Issue by AlanBreck** [brave/brave-talk#8]

**Comment by mrose17** [comment]
https://github.com/brave/brave-talk/commit/3dd12f0fd1a4d1f7faa68d7c049ccc390fb4f8d4 pushed to take advantage of `disableBeforeUnloadHandlers` ... awaiting deploy on 8x8.vc

**Comment by mrose17** [comment]
The deploy is complete. Now looking at how it "feels"...

**Comment by stephendonner** [comment]
> The deploy is complete. Now looking at how it "feels"...

I like it, a lot.  The `Leave` and `Cancel` dialog seems very apt.

**Comment by mrose17** [comment]
i agree. you just have to remember to push the red disconnect button at the bottom if you don't want the dialog. (that requires some new muscle memory for me...)
