### ISSUE TITLE
TODO: Web3 Brave Talk 

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#818]
# notifications

1. when nft/poap calls fail, report this to the user.

2. whenever reporting, put the text above the button (not below) and make the text larger and bolder. here is what we see now:
<img width="1552" alt="Screen Shot 2023-04-20 at 04 59 56" src="https://user-images.githubusercontent.com/400552/233316514-39f16beb-0f21-4eaf-bf66-8dccbab5ea4b.png">

3. cf., https://github.com/brave/brave-talk/issues/832

# minor styling

4. when mousing over the Avatar NFTs, the user should see a tooltip with the title of the NFT or collection

5. style the "Call permission type" text to be the same size as the drop-down text for "NFT Collection / POAP"

# non-premium/premium

6. if a premium subscriber, the text should be "Start premium Web3 call" instead of "Start free 1:1 Web3 call"

7. cf., https://github.com/brave/brave-talk/issues/821

8. cf., https://github.com/brave/brave-talk/issues/823

# change of address for wallet

9. if you change wallet addresses (or turn off access), we need to redo the NFT/POAP calls, cf., https://wallet-docs.brave.com/ethereum/provider-api/events/#accountschanged

**Comment by johnhalbert** [comment]
@mrose17 @tackley I have a question regarding the first item in the above list.

Here is the original implementation of `notice`: https://github.com/brave/brave-talk/blob/web3-login/src/utils.ts#L16-L36
And here is the only reference we're left with after migrating to React: https://github.com/brave/brave-talk/blob/web3-on-reactify/src/components/JoinCallSection.tsx#L31

I don't think the latter achieves the same thing as the former.  Also I don't think that the element from line 30 of the original implementation exists anywhere at this point.  @tackley am I correct in my understanding?

Is what we need here to reimplement the original `notice` function?  And if yes, do we need to either 1. remove the code in lines 30-35 or 2. reintroduce an element with the proper id as expected on line 30?

@mrose17 we discussed this previously, but I'm still a bit confused.

**Comment by tackley** [comment]
`notice` was originally a global function that directly manipulated the dom, as you link to in your first link. As you point out @johnhalbert that isn't a viable approach in the react world: mixing direct dom manipulation with react's shadow dom approach is a recipe for issues.  Instead each component that can generate errors that need to be displayed to the user should dispatch that error to their parent, which should store the current message in their (or their parent's) state and render if present, as `JoinCallSection` does in the second link. 

In fact, looking more deeply, the current notice value is stored within the call setup state [here](https://github.com/brave/brave-talk/blob/web3-on-reactify/src/hooks/use-call-setup-status.ts#L106). This is the appropriate react way of doing this.

So we should not attempt to reproduce the original approach of a single global function.  But we should ensure that we have a viable approach for displaying user-friendly (and translatable) error messages during web3 call setup, just as we do on non-web3 call setup - looks like the infra is there to set the notice within the call setup, are we just not rendering the value?

**Comment by mrose17** [comment]
Agreed. I'd like the functionality of the old `notice` ... i don't care about the mechanism, whatever is consistent with `react` is fine with me.

**Comment by mrose17** [comment]
Everything on the TODO list here (that's not in a separate issue) is now resolved! Fixed by https://github.com/brave/brave-talk/pull/830
