### ISSUE TITLE
Failed to connect wallet message when Wallet onboarding is triggered

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#819]
### Description
Failed to connect wallet message when Wallet onboarding is triggered

### Steps
1. Create a new browser profile
2. Visit `https://talk.brave.software` and click on `Start Web3 Call` 
3. Triggers wallet onboarding
4. Finish Wallet onboarding and go back to Brave Talk tab
5. Remains at `Failed to connect wallet` message doesn't trigger a page refresh automatically to connect to Wallet 

### Actual Result

https://user-images.githubusercontent.com/17010094/233549838-16091500-612c-4489-93c1-61feb9ef4ee8.mp4

### Expected Result
Once onboarding is done closing wallet tab or switching back to Talk tab should trigger page refresh to connect Wallet and create the call

cc: @mrose17

**Comment by mrose17** [comment]
@johnhalbert - Sri shows both the problem and points to a solution.

When we display `Failed to connect wallet`, there should be some additional text saying `Please click on the Wallet icon to try again.`

@mattmcalister  / @jamesmudgett - do you agree? can we find out who owns https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ and ask them to add an FAQ: "What to do if a site says that it failed to connect to the wallet?", and the answer, of course is, if you want to try again, please click on the wallet icon.

@srirambv - FYI: it isn't possible for the site to trigger the wallet widget to appear (if a website could do that, they'd be able to perform a denial of service attach).

**Comment by mattmcalister** [comment]
Yes, this seems good: 

`Failed to connect wallet. Please click on the Wallet icon to try again.`

`[Help with Brave Wallet](https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ)`

**Comment by srirambv** [comment]
Can we say `Failed to connect wallet. Please reload the page and try again` ? Since we are looking for wallet connect on page load. There isn't anything being done on the wallet icon itself

**Comment by johnhalbert** [comment]
@mattmcalister @srirambv @mrose17 pushed this change with a combination of text from @mattmcalister and @srirambv.  Reads:

`Failed to connect to wallet. Please reload the page and try again`

`[Help with Brave Wallet](https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ)`

**Comment by mrose17** [comment]
@srirambv - we think this is addressed. please retest. thanks!

**Comment by srirambv** [comment]
Looks fixed. Text change is as per https://github.com/brave/brave-talk/issues/819#issuecomment-1518274449  and `Help with Brave Wallet` links to `https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ`


![image](https://user-images.githubusercontent.com/17010094/233887722-c0001052-0002-42c9-888e-e1028bb42f4c.png)


Closing the issue
