### ISSUE TITLE
Cancel Sign request spits out JSON response instead of cancelled message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#820]
### Description
Cancel Sign request spits out JSON response instead of cancelled message

### Steps
1. Clean browser profile
2. Create a new Brave Wallet
3. Visit `https://talk.brave.software` and create a Web3 Talk room
4. Click on `Start 1:1 Web3 call` button 
5. Cancel Sign request prompt
6. JSON output is shown instead of cancelled message

### Actual Result
![image](https://user-images.githubusercontent.com/17010094/233551117-aeb8f05f-dd25-44ac-af15-eeddd9c7970d.png)

### Expected Result
Have a well formatted message instead of JSON response

**Comment by mrose17** [comment]
@johnhalbert - in this case, the json needn't be displayed only `user rejected action`.

@mattmcalister - would you prefer other wording? if so, what?

**Comment by mattmcalister** [comment]
How about:

`Unable to complete request. Please try again.`

**Comment by mrose17** [comment]
The message is generated because the user clicked "Cancel" instead of "Sign". So perhaps the better text would be "You cancelled the request."

or, if you prefer "How DARE you!"

**Comment by srirambv** [comment]
Looks fixed. Now shows `Sing request cancelled` instead of JSON response

Start Web3 Call | Join Web3 Call
-- | --
![image](https://user-images.githubusercontent.com/17010094/233906039-e6d4be60-b3d6-4cf4-aa97-d85f19b73d08.png) | ![image](https://user-images.githubusercontent.com/17010094/233906937-dbce0d06-b6a9-4646-b13c-dad9416e6e0e.png)
