### ISSUE TITLE
No option to go to premium page when trying to start a web3 call without premium account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#821]
### Description
No option to go to premium page when trying to start a web3 call without premium account

### Steps
1. Clean profile
2. Restore wallet which has NFTs/POAPs
3. Visit `https://talk.brave.software` and click on `Start a Web3 Call`
4. Sign wallet access request
5. Select NFTs/POAPs listed 
6. Click on `Start 1:1 Web3 call`
7. Shows `Sorry, you are not a subscriber` but nothing more
8. Console shows `Web3 Calls Require Brave Talk Premium Subscription`

### Actual Result
![image](https://user-images.githubusercontent.com/17010094/233553755-fa2ac641-03ee-4e6b-a4a7-537a942da8f2.png)

### Expected Result
Probably better to show the response message on the page and have a link for `https://account.brave.com/` to navigate for subscription

### Additional info
cc: @mrose17

**Comment by mrose17** [comment]
@johnhalbert - this is the same as item 7 in my TODO list -- https://github.com/brave/brave-talk/issues/821 -- i'll remove it in favor of this issue.

**Comment by mattmcalister** [comment]
![image](https://user-images.githubusercontent.com/71029/233687667-8f64f3ba-9f47-4715-954c-a6d4d9cb99f6.png)

Intro copy: `Create a Web3 video call with token-gated access controls. Select a unique NFT avatar, assign moderator privileges using POAPs, and more.`

Button: `Signup to host a Web3 call`

`A Brave Talk Premium account is required in order to host Web3 calls. Start your free trial now.`

Link to FAQ: `Learn more about Web3 calls with Brave Talk`

**Comment by johnhalbert** [comment]
@mattmcalister @mrose17 do we want to display the text `A Brave Talk Premium account is require...` if they're a subscriber?  Right now I have it so that doesn't display if they're subscribed to talk premium.

**Comment by mattmcalister** [comment]
good point. the original button was good if you are already logged in and have an active Premium subscription

**Comment by mrose17** [comment]
@mattmcalister - here is what we have now. how does this look?
![Screen Shot 2023-04-21 at 17 45 52](https://user-images.githubusercontent.com/400552/233739495-765ef171-cd4f-4e85-b55c-6288bdfe483f.png)

**Comment by mrose17** [comment]
@srirambv - @johnhalbert pushed the fix yesterday, so reading for testing

**Comment by srirambv** [comment]
Changes look good. But shouldn't `Select **a** unique NFT avatar` be `Select **an** unique NFT avatar`?

![image](https://user-images.githubusercontent.com/17010094/233888944-fff4d318-14f9-4afd-8929-e4f35ae600af.png)

**Comment by mrose17** [comment]
Oddly enough, in english "a unique" is considered correct. go figure...

**Comment by mrose17** [comment]
well, after checking a grammar checker, apparently either works. so we'll change it, but ultimately our "wording czar" will make a final determination...

**Comment by johnhalbert** [comment]
@srirambv this is ready for re-test.
