### ISSUE TITLE
Dropdown chevron should be in alignment with the expand/collapse buttons 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#822]
### Description
Dropdown chevron should be in alignment with the expand/collapse buttons 

### Steps
1. Visit `https://talk.brave.software`
2. Click on `Start a Web3 call`
3. Connect Wallet and continue
4. Dropdown chevron isn't aligned with +/- buttons 

### Actual Result
![image](https://user-images.githubusercontent.com/17010094/233556339-c74f274b-8202-4b77-848b-5c62eddea1fa.png)

### Expected Result
![image](https://user-images.githubusercontent.com/17010094/233561001-f258c5d2-6b4a-407b-aac2-cd45082411c2.png)

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
@johnhalbert - if this is _a really easy_ fix, fine; if not, it can wait until post-FCS.

**Comment by tackley** [comment]
That drop down is ugly (since we're using a native drop down) - I'm exploring whether I can make them buttons instead.

**Comment by mrose17** [comment]
Fixed by #834

**Comment by srirambv** [comment]
Looks much better 

POAP | NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/233900770-65f1079c-b078-43fa-94fa-4ca6a9acc695.png) | ![image](https://user-images.githubusercontent.com/17010094/233900792-b405cfca-cfa2-460c-9468-2b5a39969b8f.png)

Just a suggestion, can we make the selected tab to be highlighted better? Maybe something like this

![image](https://user-images.githubusercontent.com/17010094/233902083-1ebb629b-c111-4a9c-bed0-362a40b7a43d.png) | ![image](https://user-images.githubusercontent.com/17010094/233902037-51ed92fd-b265-4bcb-9aa4-48d15cd4a7a6.png)
 -- | --
