### ISSUE TITLE
fix "not a subscriber" diagnostic to reflect the actual error...

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#823]
### Description
Show proper message when a user doesn't select any POAP/NFT when creating a Web3 Talk room

### Steps

1. Create a premium subscription for Talk
2. Create a room
3. Do not select required NFT/POAP 
4. Click on `Start Web3 call`
5. Shows `Sorry, you are not a subscriber` message instead of showing the actual reason

### Actual Result

https://user-images.githubusercontent.com/17010094/233566048-08bea28d-fdb4-4496-a1a0-6037fa2ca82c.mp4

### Expected Result
Should show the actual reason for not creating the room

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
@srirambv - i think that this is a different bug, specifically that sometimes the browser seems to lose track of the fact that a user is a subscriber. i occasionally see the same error when I do select POAPs or NFTs.

i've changed the title to reflect this. if you disagree, please let me know so we can drill down a bit.

**Comment by tackley** [comment]
The actual error is being hidden by that message. I can see from this interaction that the correct subscription cookies were set, the subscription server returned the error:

`body: {"message":"Unable to verify web3 authorizations; error id: 9937e4fd-2dbd-4ff9-b68e-5f8ff86c41a3: No ADs given","code":400}`

But chose to display the message "Sorry, you are not a subscriber", presumably as a catch-all error message.

![Screenshot 2023-04-21 at 16 50 23](https://user-images.githubusercontent.com/51444/233680821-0775e7c7-75e0-4f63-b52a-b73232496f82.png)

**Comment by mrose17** [comment]
so, two things:

first, instead of "Sorry, you are not a subscriber" we should display `body.message`

second, do we know why the subscription service says it's unable to verify?

**Comment by johnhalbert** [comment]
@mrose17 I've pushed a fix for this.  The messages returned from subscriptions are not well formatted for display on the client.  So, instead of doing that I've updated the client to validate the request and print the appropriate message when a 400 is returned.

@srirambv this is ready for re-testing.

**Comment by mrose17** [comment]
hmmm... OK, let me see what kind of errors i see. cf., https://github.com/brave/brave-talk/issues/850

**Comment by srirambv** [comment]
This is fixed now. I see the error `Please choose one or more POAPs for participants` or `Please choose one or more NFT collections for participants`. 

https://user-images.githubusercontent.com/17010094/234193387-e363fe23-aed6-4a05-8370-1759a7910d62.mp4


@johnhalbert @mrose17 with selecting just moderator POAP/NFT the call room gets created. Should the message read to either select the required POAP/NFT or moderator POAP/NFT ?
