### ISSUE TITLE
Low resolution image for Brave Talk on wallet connect panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#824]
### Description
Low resolution image for Brave Talk on wallet connect panel

### Steps

1. Create Web3 Talk room
2. Wait for Wallet panel to open
3. Has a very pixelated image for Brave

### Actual Result
![image](https://user-images.githubusercontent.com/17010094/233579586-101238b3-ddfa-4eb5-a37f-0720731b5f2f.png)

### Expected Result
Good resolution image on wallet panel

### Additional Information
cc: @mrose17 @brave/design-team

**Comment by mrose17** [comment]
@srirambv - i can't reproduce this. could you create a video for me to watch? thank you!

**Comment by srirambv** [comment]
Sure here's a recording for both moderator and participant

Moderator | Participant
-- | --
<video src=https://user-images.githubusercontent.com/17010094/233662973-faec2f6c-17b6-473c-abca-e0e96d465db6.mp4> | <video src=https://user-images.githubusercontent.com/17010094/233662921-7dbbdfed-2fdc-4580-94af-5253538e1007.mp4>

**Comment by tackley** [comment]
Hmm I wonder where it's picking up the icon from. Is it the favicon, one of the images from the manifest, or taken from the opengraph meta tags?

**Comment by mrose17** [comment]
cc: @HEagle18

**Comment by srirambv** [comment]
This is a Wallet UI issue not related to Talk. I see low resolution images even when connecting to other dapps as well. Logged https://github.com/brave/brave-browser/issues/29969 for it and closing this one

**Comment by mrose17** [comment]
@srirambv - is this reproducing? did the wallet folks indicate where they are getting the favicon?

**Comment by srirambv** [comment]
It still reproduces. Here's what @Douglashdaniel said about the image resolution in [the issue](https://github.com/brave/brave-browser/issues/29969#issuecomment-1524099860)


> We cant control the resolution that a DApp serves for the fav icon on their own site, it's usually just enough for browsers tab.
> 
> The src in our front-end code is using chrome://favicon/size/64@1x/ and the style uses 40px or 48px depending on the screen, so 64 should be more than sufficient. I've attempted other sizes and it doesn't make a difference.
> 
> I think this is something out of our control, unless we have a mapping of popular DApps with their logo's, but that would also probably come with it's own security risks, since a domain could change their fav icon at any time.

**Comment by mrose17** [comment]
ok, here is the fix:
1. create `/public/favicon.ico` that is a 64x64 icon of the Brave Talk icon
2. add `public/images/brave-talk-64x64.png` for completeness
3. update `public/manifest.json` to include reference to the new png

**Comment by srirambv** [comment]
Brave Talk icon seems fine but still a little pixelated around the edges 
![Sl26xlUqK51](https://github.com/brave/brave-talk/assets/17010094/9ec8e090-0bbc-4e2c-af81-7e4aefa58691)

**Comment by mrose17** [comment]
@johnhalbert - can you remind me which image, exactly are we using for this?

@Douglashdaniel - your thoughts?

**Comment by mrose17** [comment]
also, are we using an image with a transparent background? in looking at the video attached to https://github.com/brave/brave-talk/pull/917 ... i don't think that's the case! sorry for the nuance...

**Comment by johnhalbert** [comment]
@mrose17 here are the images being used:

https://github.com/brave/brave-talk/blob/dev/public/images/brave-talk-192x192.png
https://github.com/brave/brave-talk/blob/dev/public/images/brave-talk-180x180.png

**Comment by johnhalbert** [comment]
@mrose17 I used Gimp to do the editing on these.  I'm seeing transparent backgrounds on all the images above.  And in the video from #917 you can see the favicon is updated and appears to have a transparent background as well.

**Comment by aguscruiz** [comment]
Hi @johnhalbert you can export the icons from this Figma File if you want, I created a preset to export the same sizes you listed above

https://www.figma.com/file/ycXqw8euy6z41uXrlDni6K/Desktop-Brave-Talk?type=design&node-id=3099-57242

Also added a .svg export so you can create the .ico from it

**Comment by johnhalbert** [comment]
@aguscruiz ok on the preset sizes.  Can you help me with the .ico?  I'm probably not generating these correctly and would rather defer to someone who had expertise on this.

**Comment by aguscruiz** [comment]
Sure. I think this one should work, let me know how it goes

[brave-talk.ico.zip](https://github.com/brave/brave-talk/files/11536075/brave-talk.ico.zip)

**Comment by johnhalbert** [comment]
@srirambv this is ready for re-test

**Comment by srirambv** [comment]
@johnhalbert still seeing the low resolution image on dev. 

https://github.com/brave/brave-talk/assets/17010094/9aef9e59-a681-44d8-b5b3-d8e73652ed91

**Comment by bradleyrichter** [comment]
can we not just use the SVG that is already in place?

<img width="382" alt="image" src="https://github.com/brave/brave-talk/assets/13509546/99c6e991-f2e4-40c9-b5a0-839069b3d3f9">

**Comment by mrose17** [comment]
@bradleyrichter - i don't think we can use an `svg` directly for a favicon thing...

@johnhalbert - can you re-re-verify that the images we think are on `dev` are actually there and being referenced in the `<head/>` element?

@srirambv - can you verify exactly which icons (i.e., what exactly image URLs) are showing up pixelated and include only a screenshot (and not a video) for those? (i'm not sure that it possible to get the URL, but i thought i'd be ask)

**Comment by srirambv** [comment]
Still seeing a slightly pixelated image on the connect wallet screen. More discussion [here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1685677757366059)

![image](https://github.com/brave/brave-talk/assets/17010094/88baaced-ae01-44fb-b7d5-fbbdbd808f55) | ![image](https://github.com/brave/brave-talk/assets/17010094/aad6ccbe-4272-47a8-b1a4-f6b1c6d8a827)
-- | --

**Comment by mrose17** [comment]
@Douglashdaniel - the current thinking here in "Web3 Brave Talk" land is that the wallet code is actually hard-wired to look for the 64x64 icon, rather than using the first one (128x128) in the `<head/>` and in the `manifest.json` file.

can you confirm one way or another? thank you!

**Comment by Douglashdaniel** [comment]
As far as the `Front-end` code goes, it is set like so

https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/components/extension/connect-with-site-panel/connect-with-site-header/connect-with-site-header.tsx#L101

https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/components/extension/connect-with-site-panel/connect-with-site-header/connect-with-site-header.tsx#L111

```
<FavIcon
   src={`chrome://favicon/size/64@1x/${originInfo.originSpec}`}
   isReadyToConnect={isReadyToConnect}
/>
```

In my testing changing to `chrome://favicon/size/128@1x/${originInfo.originSpec}` or any other resolution wasn't making any  difference.

I'm unsure what `chrome://favicon` is deciding to return behind the scenes. Maybe we can try to bumping it again to `128@1x` and see if it makes a difference this time! :)

**Comment by srirambv** [comment]
@Douglashdaniel does bumping it to `120@1x` fix it at least for Brave Talk if not for other Dapps. There's https://github.com/brave/brave-browser/issues/29969 where you mentioned it can't be controlled for icons and is ok to set it to `64@1x/` for Dapps. I think in this case, just making sure the image resolution isn't pixelated for Brave Talk would be a good first step

**Comment by Douglashdaniel** [comment]
@srirambv I tested last night with it set to `chrome://favicon/size/128@1x/${originInfo.originSpec}` and it didn't make any difference, is still pixelated.. 

<img width="422" alt="Screenshot 36" src="https://github.com/brave/brave-talk/assets/40611140/51c8f79e-4df5-47f9-81c7-7618dd05222c">

<img width="430" alt="Screenshot 37" src="https://github.com/brave/brave-talk/assets/40611140/158abe34-5da2-48c7-a6dd-eecf8cdab816">

You can test this manually in the browser, the icon sizes change, but the resolution does not improve.

`brave://favicon/size/64@1x/https://talk.brave.com`
![Screenshot 42](https://github.com/brave/brave-talk/assets/40611140/d3348308-b4e2-46da-8838-5e078dba36ac)

`brave://favicon/size/128@1x/https://talk.brave.com`
![Screenshot 43](https://github.com/brave/brave-talk/assets/40611140/529d28b6-0cd1-428d-89d0-f42c9ee173e7)

Discussed with @petemill and he is under the impression that `chrome` will not give us a higher resolution favicon.

**Comment by kdenhartog** [comment]
Nah no concerns from me because it's a Brave origin. I wouldn't want to do this for others though at this point because it means we need to maintain another list.

**Comment by mrose17** [comment]
I have no objections to adding a check for the Brave Talk origin, though I don't think it particularly necessary...

**Comment by srirambv** [comment]
@Douglashdaniel while testing Solana support for Web3 Talk using Phantom wallet, the image that is shown on the connection window for the extension is pretty clear and also uses the `180x180` image set to `90x90` 

![image](https://github.com/brave/brave-talk/assets/17010094/875830f0-479f-4719-afb9-e72d79366739)
![image](https://github.com/brave/brave-talk/assets/17010094/8d64fc45-0922-48a6-bf20-5c548e49f601)
