### ISSUE TITLE
Every participant is shown as Moderator

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#825]
### Description
Every participant is shown as Moderator

### Steps

1. Create a Web3 Talk room using premium credentials
2. Select the NFT type for required collections when creating the room
3. Join the call with a participant NFT 
4. Join the call from a different browser with a wallet which doesn't have any NFT
5. Check participant list, shows everyone as moderator

### Actual Result
![image](https://user-images.githubusercontent.com/17010094/233585119-dd90d185-7efb-485e-a3ce-897f7c9619a4.png)

### Expected Result
Should only show the room creator as Moderator

### Additional Information
cc: @mrose17

**Comment by srirambv** [comment]
This seems fixed now. @johnhalbert did https://github.com/brave/brave-talk/pull/830 fix this one as well?

Moderator Window | Participant Window | Participant on iOS 
-- | -- | --
<img src=https://user-images.githubusercontent.com/17010094/233899894-5eaa92e7-4e45-4df4-a83c-19a95f65afc9.png> | ![image](https://user-images.githubusercontent.com/17010094/233899856-d3041181-bbb8-4711-8726-03437249e1b9.png) |<img width=300 src=https://user-images.githubusercontent.com/17010094/233900015-a39b052f-7f7f-47e7-a0c9-cb5bf4ec24e2.png>

**Comment by johnhalbert** [comment]
@srirambv I believe this subscriptions issue fixed this: https://github.com/brave-intl/subscriptions/pull/328

I made additional changes to subscriptions to fix a few other issues we found there earlier today.  Can you re-test this and see if you're still seeing the appropriate users appearing as moderators?

**Comment by srirambv** [comment]
Looks fixed 
![vJkVp0Fmeb](https://user-images.githubusercontent.com/17010094/234244515-d421cef8-05d8-4cf3-a107-58a4173ceece.png)
