### ISSUE TITLE
Able to join a Web3 call without any NFTs from required NFT collection in Wallet 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#828]
### Description
Able to join a Web3 call without any NFTs from required NFT collection in Wallet 

### Steps

1. Create a Web3 Call using Moderator NFT with Premium account
2. Select your NFT collection in the required NFTs options
3. Join the call from a different browser with a new Wallet account created on MM
4. Able to successfully join the call and get moderator status because of [#825](https://github.com/brave/brave-talk/issues/825)

### Actual Result
Able to join a Web3 call without any NFTs from required NFT collection in Wallet 

### Expected Result
Should not be allowed to join the call if the user wallet doesn't have the required NFT from a collection

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
Thanks. We've been looking into this and hope to have a resolution later today.

**Comment by johnhalbert** [comment]
@srirambv this is ready for re-test

**Comment by srirambv** [comment]
Verified. Can't join any Web3 call with a wallet that doesn't have any NFT or the required NFTs
![image](https://user-images.githubusercontent.com/17010094/234237011-4157c1b8-a85d-43f4-8eaa-4604b0c6c6c1.png)
