### ISSUE TITLE
Disconnecting from call continues to show the attendees on the last person on iOS

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#829]
### Description
Disconnecting from Web3 Call continues to show the attendees on the last person on the call

### Steps

1. Create a Web3 call with Moderator NFT
2. Join 2/3 other users on desktop
3. Join the same call on iOS making it to 4 participants
4. Leave the call on for a while
5. Disconnect call from desktop
6. iOS continues to show the participants who all disconnected and continues the call 
7. Able to restart the call with the same URL on desktop but doesn't show the user from iOS
8. Reload the Web3 Call page on iOS goes back to join screen

### Actual Result
Disconnecting from Web3 Call continues to show the attendees on the last person on the call

### Expected Result
Should not disconnect iOS user from call when there is one participant active

### Additional Information
cc: @mrose17

**Comment by mrose17** [comment]
i suspect that this is desired behavior (and is independent of whether it's Web3 Brave Talk or not).

briefly: a moderator can create a room and just leave, and other folks can continue to join/stay, etc. the room doesn't go away if the moderator does, only when the last participant leaves does the room go away.

**Comment by srirambv** [comment]
@mrose17  I think there is a little misunderstanding here. I just ran this scenario again with normal talk call and the issue seems to be on iOS specifically. Even when desktop users are disconnected from the call, iOS continues to show those participants as on the call. It continues like that until you come disconnect it or reload the page in which case it goes back to talk home page.

**Comment by mrose17** [comment]
@srirambv - just to confirm. is this web3-only or just on iOS (regardless of web3 or not)?

**Comment by srirambv** [comment]
This is on just iOS and Talk in general

**Comment by mrose17** [comment]
It happens only on iOS and only when doing Web3 Brave Talk and iOS?

or, it happens only on IOS, and it doesn’t matter which version of Brave Talk is in use by iOS?

**Comment by srirambv** [comment]
Retested this on SDK build `0.0 (23.12.11.17)`. If iOS device auto-locks, iOS continues to show the participants as connected until the disconnected message shows up. Able to rejoin the call from the popup message with all participant still on call. Also tested participant list gets updated whenever someone leaves the call so that part is working as expected with the SDK build

**Comment by mrose17** [comment]
@srirambv - so this sounds like everything is working as expected. or am i missing something? sorry for the back-and-forth ... thanks!

**Comment by mrose17** [comment]
Confirmed that the current behavior is OK.
