### ISSUE TITLE
Sign message on Android looks like a block of text. Needs better text alignment

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#831]
### Description
Sign message on Android looks like a block of text. Needs better text alignment

### Steps

1. Join a Web3 call from Android
2. Click on the join call
3. Sign message is not properly shown

### Actual Result
<img width=300 src=https://user-images.githubusercontent.com/17010094/233665874-44e61b75-e322-4554-ad53-4e8931c3b180.png>

### Expected Result
Better text alignment on Sign panel

### Additional Information
cc: @mrose17 @Pavneet-Sing

**Comment by mrose17** [comment]
cc: @HEagle18

**Comment by mrose17** [comment]
@HEagle18 - do we have this triaged (or maybe it was fixed). i recall we were going to be working on SIWE for Android, so i'm thinking maybe this has already been dealt with... thanks!

**Comment by HEagle18** [comment]
Just chatting with Sri and Pavneet. We now have an issue for it and will
get to it soon.

**Comment by simoarpe** [comment]
✅ This issue has been fixed on latest master (commit a368a1ab342f0a5d4dee4db3f2699f7d02579247).

Details section is now correctly formatted and can be accessed by tapping on "See details" in the sign in page.

<img src="https://github.com/brave/brave-talk/assets/3308503/7d6ae84b-bc82-4b10-b314-4d08dd1f6860" width="300" />
<img src="https://github.com/brave/brave-talk/assets/3308503/e45c4bfc-14f1-4a92-b947-f78160c81445" width="300" />

__👇 Demo__

https://github.com/brave/brave-talk/assets/3308503/1d86d2ea-3034-4d5f-8e93-f006e5b558a2

cc @mrose17

**Comment by mrose17** [comment]
Thank you very much!
