### ISSUE TITLE
reduce impact of web3 dependencies on non-web3 users

### ISSUE THREAD

**Issue by tackley** [brave/brave-talk#833]
The dependencies needed for web3 calls increase the size of the js bundle from 285K to 650K (non-gzipped, so actual impact is less).

We should explore whether we can use [webpack's code splitting](https://webpack.js.org/guides/code-splitting/) to make this into a separate bundle that's only loaded when the user selects a web3 call. 

(The actual gzipped size may not warrant this complexity however.)

**Comment by mrose17** [comment]
As Graham notes, it may not be necessary because of the gzipping. After FCS, we can see exactly how big this is.

**Comment by bcaller** [comment]
Based on package.json in https://github.com/brave/brave-talk/compare/dev#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 we add `apg-js`, `buffer`, `ethers`, `i18next`. All seem OK.

[apg-js](https://socket.dev/npm/package/apg-js): Not clear if this is actually used by the code, `dev/apg-lib.less` appears to get picked up by jsonToLess so can be found in the bundled JS.

[ethers](https://socket.dev/npm/package/ethers): Contains a lot more functionality than we need, but OK.

**Comment by mrose17** [comment]
the unused libraries are removed! I haven't seen any issues. it is deployed on `dev`

**Comment by hadiamjad** [comment]
I checked the file size of the main bundle.js and `ethers` adds ~28%. Here is the complete breakdown:
![image](https://github.com/brave/brave-talk/assets/46374292/7bc3ade0-6d7f-4b99-ab8f-2ad6d69d84f7)

However, the Gzip version of the bundled main is ~200kb.
`brave-talk % npx gzip-size-cli /Users/haadi/Downloads/brave-talk/html/static/main.2bcc0a095bea1eaaffc7.js.gz
200 kB`

Do we still want to do webpacks code splitting?

**Comment by mrose17** [comment]
I think we should split it. However, let's hear from @tackley as to his thoughts before doing any "real work" (-;

**Comment by tackley** [comment]
Thanks for the bundle analyser graphs @hadiamjad, that's exactly the data we needed.

If we can do it cleanly without too much additional complexity, we should do it I think, on the assumption that a significant proportion of users will not use the web3 functionality, at the moment at least. We might also be able to get some of our components/web3 code (31K non gzipped) in the web3 only bundle too.

We need to ensure that the web3 bundle only gets loaded when the user:
- joins a web3 call, OR
- clicks the button to host a web3 call

I suspect that will be the tricky part, and is where the complexity _may_ get out of control. Or it may be fairly cleanly separated in the code already and just needs a few tactical lazy component imports as outlined e.g. [here](https://blog.bitsrc.io/understanding-webpacks-code-splitting-feature-3077768e4066).

**Comment by hadiamjad** [comment]
Thanks @tackley. I'll put changes in a separate branch and from there we can discuss it.

**Comment by hadiamjad** [comment]
Ok, so I tried using dynamic imports for `ethers` in [api.ts](https://github.com/brave/brave-talk/commit/02d00a544f9b7e3a3bc47c1e88be2053aa85dee5#diff-d0e41c225aed7ec04620436e19c43080d7e6803aa4fa00f0f2aee8660d5e312e). Looks like it worked and it now loads the Ethers library as a separate chuck at the necessary point, not at the entry point. 
reference commit:  https://github.com/brave/brave-talk/commit/02d00a544f9b7e3a3bc47c1e88be2053aa85dee5
Stats below:

BEFORE: [build without dynamic load](https://github.com/brave/brave-talk/tree/abdul-reduce-web3-dependency/normal-build-html)
entry main.js has unzipped size of **~540KB** and gzipped **200kb**
![image](https://github.com/brave/brave-talk/assets/46374292/eda76f3b-a926-403d-aa9e-beb7a551e668)

AFTER: [build with dynamic load](https://github.com/brave/brave-talk/tree/abdul-reduce-web3-dependency/dynamic-build-html)
entry main.js has unzipped size of **~369KB** and gzipped **136kb**
![image](https://github.com/brave/brave-talk/assets/46374292/dfaf9ed1-7331-4244-afb2-9f3f1c5db5ce)

**Comment by tackley** [comment]
Thanks @hadiamjad. There appear to be lots of unrelated changes in the commit you reference, or perhaps you accidentally committed the generated output. Could you prepare a PR with just the changes relating to this?

As always with this kind of changes, the trade off between the increased release risk and hit to developer productivity of increased complexity against the benefit delivered is key here, so that's what I want to be able to review.

**Comment by mrose17** [comment]
@hadiamjad - i suggest that you make a fork of `main`, apply the changes, and then generate a PR for review. This should provide the smallest possible footprint to examine. thanks!

**Comment by hadiamjad** [comment]
Sorry this is the minimum change required: https://github.com/brave/brave-talk/pull/1066

cc: @mrose17 @tackley
