### ISSUE TITLE
Kicking out original moderator from call continues the call for both participants with the same URL

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#847]
### Description
Kicking out original moderator from call continues the call for both participants with the same URL

### Steps

1. Start a Brave Talk call so that you are the moderator of the call
2. Add multiple participants to the call
3. Assign one of the participant moderator status
4. Kick out the original moderator from the new user with moderator rights
5. Original moderator is kicked out of call but continues to be on the call with a message
6. Other participants continue to be on the call 
7. Both kicked out user and active participants in the call are still using the same URL.  

### Actual Result

https://user-images.githubusercontent.com/17010094/233908909-334e6a36-5379-4208-9524-0553cb6ddfee.mp4

### Expected Result
Should disconnect the call to the person being kicked out

### Additional Information

**Comment by mrose17** [comment]
@srirambv - is this specific to web3 or not?

**Comment by srirambv** [comment]
Not specific to Web3. Talk in general

**Comment by mrose17** [comment]
i'm moving this to https://github.com/jitsi/brave-tracker/issues/120
