### ISSUE TITLE
Joining a Web3 Call created by participant still marks you as a moderator

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#848]
### Description
Joining a Web3 Call created by participant still marks you as a moderator

### Steps

1. Create a premium account and link Wallet which has participant NFT/POAP
2. Create a Web3 call by selecting the Participant POAP for both required and moderator fields
3. Room is created with participant id set as moderator
4. Join the call call with wallet that has premium account linked and has both Moderator and Participants POAP linked
5. Both participants are marked as moderators

### Actual Result

Participant on iOS | Moderator join from Desktop
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/233911358-37e94d50-adbd-4c75-bfed-41921b6e1d89.png> | ![image](https://user-images.githubusercontent.com/17010094/233911277-dc90eedf-6321-419b-be90-b75d9efa3f93.png)

### Expected Result
Wallet with moderator NFT/POAP should join the call without any moderator priveleges

### Additional Information
cc: @johnhalbert @tackley @mrose17

**Comment by mrose17** [comment]
@srirambv - how does this differ from https://github.com/brave/brave-talk/issues/825 ?

**Comment by srirambv** [comment]
@mrose17 the issue with #825 is fixed now only the person hosting the call shows as Moderator. The problem here is if you have an NFT/POAP of participant and you host a call so you become the moderator, and if anyone with a Moderator NFT/POAP joins the call they also are shown as moderator. Its a bit different from what was seen in #825

**Comment by johnhalbert** [comment]
@srirambv I found that this was happening for NFT  collection auth.  I did not see it happening for POAP auth.
I've addressed this and it's ready for re-test.

**Comment by srirambv** [comment]
This looks fixed. Ran the following scenarios

Scenario 1:
- Wallet with participant NFT creates a Web3 Talk room and is set as moderator
- Doesn't specify any NFT/POAP for required/moderator settings when setting up the call
- Wallet with moderator NFT joins the call, doesn't get added as moderator

Scenario 2:
- Wallet with participant NFT creates a Web3 Talk room and is set as moderator
- Only specifies which NFT/POAP is required for joining the call. Nothing is set for moderator setting
- Wallet with moderator NFT joins the call, doesn't get added as moderator 

Scenario 3:
- Wallet with participant NFT creates a Web3 Talk room and is set as moderator
- Specifies both required POAP/NFT and moderator settings for joining the call
- Wallet with moderator NFT joins the call, gets added as moderator to the call since it has the specified NFT/POAP to get moderator privileges

POAP | NFT
-- | --
<video src=https://user-images.githubusercontent.com/17010094/234468692-781c319b-b795-40ed-a161-4aeb9cd435a8.mp4> | <video src=https://user-images.githubusercontent.com/17010094/234468673-b2ecb995-7e94-415d-8a6e-70319acf9a66.mp4>
