### ISSUE TITLE
do not require POAPs or NFTs for Web3 room creation

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#850]
if i start a web3 call without specifying the call permission type, I get "Please choose one or more NFT collections for participants" or "Please choose one or more POAPs for participants". The specification doesn't require this, and the elements of procedure in the spec are specifically written to allow for an empty list!

**Comment by srirambv** [comment]
This works fine. Able to create a Web3 call without pre-selecting any POAP or NFT. Also verified when a Web3 call is created without any POAP/NFT requirement able to join the call by connecting wallet that doesn't have any NFT/POAP. 

https://user-images.githubusercontent.com/17010094/234469269-3ca411e3-ddf2-48cd-ae04-65b807c4a0d5.mp4
