### ISSUE TITLE
Error Message is not removed when there is a pending request and user reloads the page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#851]
### Description
Error Message is not removed when there is a pending request and user reloads the page

### Steps
1. Create wallet on MM 
2. Open a Web3 Talk link to join
3. Ignore the Wallet connect request on MM
4. Reload the page, shows failed to connect message but MM still has connection request pending
5. Approve wallet connect on MM
6. Page reloads with Wallet details to join the call but doesn't remove the failed to connect message 

### Actual Result

https://user-images.githubusercontent.com/17010094/234240542-735fb679-bf35-4c5a-86b7-2b6c0f2f283a.mov

### Expected Result
Error message should be removed when wallet is connected successfully

### Additional Information
@mrose17 @johnhalbert

**Comment by johnhalbert** [comment]
@srirambv this is ready for re-test

**Comment by johnhalbert** [comment]
Also worth noting this appears to only have affected Metamask wallet and not Brave wallet. @mrose17 @srirambv

**Comment by srirambv** [comment]
This looks fixed. Error message is not retained when connecting wallet

https://user-images.githubusercontent.com/17010094/234467132-23ed6b93-8e9e-4c93-b930-3d5e85a2eb4c.mp4
