### ISSUE TITLE
`background-image` zooms when `background-size` changes due to expanding drop-downs

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#855]
Although I *personally* find this behavior charming, everyone else dislikes it... so, the appropriate CSS incantations should be applied to keep the `background-image` the same size. perhaps https://stackoverflow.com/questions/56846228/how-do-i-stop-background-image-from-zooming-in-because-of-background-size-cover may be of interest (h/t: @johnhalbert). it has also been suggested that the drop-downs animate when expanding/collapsing.

Everything collapsed:
![Screen Shot 2023-04-25 at 11 02 12](https://user-images.githubusercontent.com/400552/234319394-2719add5-13ea-429c-9ce8-e7e524feda09.png)
One drop-down expanded:
![Screen Shot 2023-04-25 at 11 02 22](https://user-images.githubusercontent.com/400552/234319517-26b63fe1-6844-4e46-9561-327968d075d0.png)

**Comment by tackley** [comment]
Should be addressed with https://github.com/brave/brave-talk/commit/6fb8e83baac29b6d343b1fc95b913e6cc176b8b1

**Comment by johnhalbert** [comment]
@srirambv this is ready for re-test.

**Comment by srirambv** [comment]
This is fixed now. Background image doesn't zoom in when expanding dropdowns

https://user-images.githubusercontent.com/17010094/234463706-21c4de10-5d3d-409b-8c94-fef41c45a940.mp4
