### ISSUE TITLE
Stronger warning on 24 hour video recording expiry

### ISSUE THREAD

**Issue by lukaslevert** [brave/brave-talk#863]
![image](https://user-images.githubusercontent.com/79997955/235192471-69bed3c8-9dab-422b-ba83-6cc6859281ec.png)

A partner recently shared that they did not download a video recording of a Talk meeting and ultimately lost access to it due to the 24 hour privacy expiry. This may suggest that it isn't clear enough for a certain % of users.

I propose clarifying the text with explicit terms like "warning, deleted, and file loss" to ensure users fully understand the limitations of the platform with regards to video recordings.

Suggested copy: 

_Warning: Recordings are automatically deleted after 24 hours. Avoid file loss by downloading the video file shortly after your Talk session ends._

CC @rmcfadden3 to provide copywriting oversight.

**Comment by mrose17** [comment]
A complimentary feature might be to trigger a notification if a recording is in progress and the moderator clicks the "Leave the meeting" button. The notification could ask the moderator whether they want to stop recording.

This might cause more problems than it solves, however.

**Comment by rmcfadden3** [comment]
@lukaslevert — I like your copy suggestion. No additional edits from me.

**Comment by mrose17** [comment]
Moving to https://github.com/jitsi/brave-tracker/issues/121
