### ISSUE TITLE
Pretty format sign cancel request message on iOS

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#882]
### Description
Pretty format sign cancel request message on iOS

### Steps
1. Connect wallet to join Web3 call
2. Cancel the sign message request
3. Shows actual error message rather than `Sign request cancelled`

### Actual Result

https://user-images.githubusercontent.com/17010094/236263969-b49952d9-f62f-4060-8a47-98f77bd2b3e6.MP4

### Expected Result
Pretty formatted `Sign request cancelled` message when a user cancels the sign message

**Comment by StephenHeaps** [comment]
I can't assign myself this issue, but this should be resolved on iOS-end with https://github.com/brave/brave-ios/issues/7392. Targeting v1.51.

**Comment by mrose17** [comment]
cc: @HEagle18

> I can't assign myself this issue, but this should be resolved on iOS-end with [brave/brave-ios#7392](https://github.com/brave/brave-ios/issues/7392). Targeting v1.51.

@StephenHeaps - thanks!

**Comment by srirambv** [comment]
This is fixed and verified as part of https://github.com/brave/brave-ios/issues/7392#issuecomment-1537807139
