### ISSUE TITLE
Ethereum address exceeds horizontal view bounds on mobile

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-talk#883]
After you connect your wallet / ethereum address to Brave Talk Web3, the address is displayed in a single line that exceeds the horizontal bounds of the view / device screen. This causes minor UX issue where the view scrolls horizontally and vertically, when it should only need to scroll vertical.

I noticed this on iOS but it may exist on Android too.

https://user-images.githubusercontent.com/5314553/236297412-41f4989f-7b12-434a-8fde-f13f75ab56c3.mp4

**Comment by johnhalbert** [comment]
@srirambv this is ready for testing.

**Comment by srirambv** [comment]
Verified changes look good on dev. Ethereum address is within bounds on mobile. Verified for both mobile view and desktop view

https://user-images.githubusercontent.com/17010094/236993093-6bb6e2a3-fdec-4252-8494-ff92f22db669.MP4
