### ISSUE TITLE
Create public brave-talk repository

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#9]
with master, staging, and development branches for the beta site. the alpha site branches can stay here.

before releasing, please have a security review to ensure we aren't leaking anything...

also: we would keep this repo private, just mark it deprecated...

- [x] create brave-talk private repo
- [x] ensure the github secrets necessary for deployment are copied across from brave-together (these are used by .github/workflows) - this will need devops support:
    - AWS_DEVELOPMENT_ACCESS_KEY_ID
    - AWS_DEVELOPMENT_SECRET_ACCESS_KEY
    - CLOUDFRONT_DEVELOPMENT_DISTRIBUTION_ID
    - AWS_STAGING_ACCESS_KEY_ID
    - AWS_STAGING_SECRET_ACCESS_KEY
    - CLOUDFRONT_STAGING_DISTRIBUTION_ID
    - AWS_PRODUCTION_ACCESS_KEY_ID
    - AWS_PRODUCTION_SECRET_ACCESS_KEY
    - CLOUDFRONT_PRODUCTION_DISTRIBUTION_ID
- [x] extract latest revision only of `development-beta`, `staging-beta` and `master-beta` to that repo, dropping the beta suffix
- [x] disable deployment from brave-together
- [x] ensure deployment to all environments works from brave-talk
- [x] ensure the `development-dev` branch works too

At this point all development must move to brave-talk.

- [x] enable dependabot
- [x] transfer all open issues
- [x] replace the default branch readme on this repository to point to brave-talk
- [x] archive this repository, ensuring that new issues and new commits cannot be added
- [x] raise security review for making `brave-talk` public
- [x] after completion, switch from private to public

**Comment by tackley** [comment]
now public
