### ISSUE TITLE
Join without audio dropdown isn't properly aligned 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#904]
### Description
Join without audio dropdown isn't properly aligned 

### Steps to reproduce
1. Open a Brave talk link
2. Click the drop down to start the call without audio
3. Dropdown alignment is off

### Actual Result

https://github.com/brave/brave-talk/assets/17010094/538b199d-fecc-46cc-98ed-19b74959e3be

### Expected Result
Should align properly

### Additional Information
Note: This is a general Brave Talk issue and not specific to Web3

cc: @mrose17

**Comment by shubrautt** [comment]
@mrose17 @srirambv can I work on this issue?

**Comment by shubrautt** [comment]
@mrose17  can I work on this issue?

**Comment by mrose17** [comment]
@shubrautt - hi! thanks for volunteering. before doing anything, please let me check with someone to see if this is an SDK issue or not; if so, there's an entirely different code path to investigate first!

**Comment by shubrautt** [comment]
@mrose17 okay, thank you..!

**Comment by saghul** [comment]
This is a mobile web issue, we'll take a look!

**Comment by mrose17** [comment]
@saghul - thanks

**Comment by mrose17** [comment]
Moved to other issue "bucket".
