### ISSUE TITLE
Web3 Talk should recognize the correct account that is used to connect to the site

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#908]
### Description
Visiting a Web3 talk room automatically recognizes only the first account. If the user connects to a different account it isn't automatically updated 

### Steps to reproduce
1. Create a Wallet on Beta and host a Web3 call using that wallet
2. Create a Wallet on Nightly, add 2 accounts to the wallet
3. Open the Web3 talk link in Nightly, automatically detects the first account of the wallet and shows the address on the page
4. Click on `Join web3 call` 
5. Brings up the connect account  modal on wallet
6. Select the 2nd account and connect to the site
7. Page continues to show the account 1 address 
8. Click Join Web3 call, Shows `Error signing message` but console throws `invalid account` message
9. Reload the page 
10. Now shows the correct account address that is connected
11. Click on Join web3 call
12. Brings up the message sign prompt to join the call and it works

### Actual Result

https://github.com/brave/brave-talk/assets/17010094/0b8c5fb4-d1b3-41d9-b9e0-15db3ca101a6

### Expected Result
Should detect the correct account when showing the page so user doesn't run into this issue

### Additional Info
cc: @mrose17 @johnhalbert

**Comment by johnhalbert** [comment]
@srirambv this is ready for re-test.

**Comment by srirambv** [comment]
This is fixed. Able to see the correct account that is selected to connect to the site

https://github.com/brave/brave-talk/assets/17010094/61d2cdf1-682c-4d8e-9953-1a2b34452101
