### ISSUE TITLE
Unable to create Web3 Talk calls on Staging

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#909]
### Description
Unable to create Web3 Talk calls on Staging

### Steps
1. Try creating a Web3 talk room on staging

### Actual Result
![image](https://github.com/brave/brave-browser/assets/17010094/05785891-ccdf-468d-9885-cc13202443cd)

### Expected Result
Create a new Web3 Talk room

### Additional Info
cc: @mrose17 @johnhalbert

**Comment by mrose17** [comment]
@srirambv - i can't reproduce this on either `nightly` or `release`...

**Comment by srirambv** [comment]
Closing the issue as ot can't be reproduced anymore.
