### ISSUE TITLE
allow room creation with an exception list...

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#920]
allow the user to specify one or more addresses (grouping using NFTs or POAPs doesn't really make sense in this context), cf., https://docs.google.com/document/d/193d9IQa33QfnxHnSW-lrv3PgjW2ztZXQuSqQW3nxVYU/edit#heading=h.ycyh8w19cvd2

**Comment by srirambv** [comment]
Verified able to setup Premium Brave Talk rooms on the following browsers on Desktop

**Chrome** - ✅ 

https://github.com/brave/brave-talk/assets/17010094/6785c7dd-f85a-4b48-b0bb-453b4d5ff11d

**FireFox** - ✅ 

https://github.com/brave/brave-talk/assets/17010094/6c6303fe-cc9a-4a32-bd14-5314adfb25fb

**Opera** - ✅ 

https://github.com/brave/brave-talk/assets/17010094/a38ae403-d49b-465c-b2c9-4a2143bc0934

**Edge** - ✅ 

https://github.com/brave/brave-talk/assets/17010094/c23d4e5d-3d64-4732-9ac2-7fc3e9146d71

**Safari** - ✅ (exception is can't create a meeting link to share)

https://github.com/brave/brave-talk/assets/17010094/75c4309f-e6cf-4aa6-aea5-8627a79dc72a

**DuckDuckGo** - ✅ (exception is can't create a meeting link to share)

https://github.com/brave/brave-talk/assets/17010094/bc3df124-3f80-423a-b948-6a39d1d6e733

**Comment by srirambv** [comment]
Verified able to setup premium calls on the following browsers on Android/iOS

<table>
<tr>
<td  rowspan="2"><b>Chrome</b></td>
<td>Android</td>
<td>iOS</td>
</tr>
<tr>
<td> ✅ </td>
<td> ✅ </td>
</tr>
<tr>
<td  rowspan="2"><b>Firefox</b></td>
<td>Android</td>
<td>iOS</td>
</tr>
<tr>
<td> ✅ </td>
<td> Partial ✅ (able to start but no support for 8x8 message is shown</td>
</tr>
<tr>
<td  rowspan="2"><b>Edge</b></td>
<td>Android</td>
<td>iOS</td>
</tr>
<tr>
<td> ✅ </td>
<td> Partial ✅ (able to start but no support for 8x8 message is shown </td>
</tr>
<tr>
<td  rowspan="2"><b>Safari</b></td>
<td>Android</td>
<td>iOS</td>
</tr>
<tr>
<td> ❌ (No Safari support)</td>
<td> ✅ </td>
</tr>
</table>

Note: iOS doesn't provide an option to `Create link` option when premium account is enabled

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/brave-talk/pull/1223
