### ISSUE TITLE
After Web3 call, NFT avatar remains in non-Web3 calls

### ISSUE THREAD

**Issue by bcaller** [brave/brave-talk#966]
There is no way to remove the NFT avatar from the UI. You need to clear local storage.

Not sure if we should always hide the avatar in non-Web3 calls (since you can't normally select an avatar), or provide an option to hide it.

**Comment by mrose17** [comment]
After consideration, here is the way forward: if the avatar is set in a Web3 call, then it should be put into `localStorage` ...

It would be ideal to be able to use the avatar and not store it; however, that may be difficult to implement. as such, it may be better to simply add a hook on receiving an event such as`dataChannelOpen` (which occurs after the avatar is set and stored) to remove the value from `localStorage`.

**Comment by srirambv** [comment]
There seems to be an issue with picking the right avatar. 

https://github.com/brave/brave-talk/assets/17010094/b53e6b88-5844-499b-a77d-d7a9abe7821b

**Comment by srirambv** [comment]
This is mostly fixed for the part where non-web3 calls use the default avatar. But selecting an avatar for Web3 calls is showing the wrong one when call is initiated

**Comment by srirambv** [comment]
The following scenarios checks out right.

* For Web3, select an avatar before starting call and the same avatar shows as expected - ✅ 
* For Web3, going back to the same room, the same avatar is shown for the call - ✅ 
* For Web3, going to a different room and not selecting an avatar, doesn't show any avatar - ✅ 
* For Web3, going to a different room and selecting a different avatar shows the new avatar selected - ✅ 
* For non-Web3, no avatar selected from Web3 call is shown when creating and joining the call - ✅
